### ISSUE TITLE
STI и изменение типа сущности 

### ISSUE THREAD

**Issue by butschster** [cycle/orm#101]
Всем привет!

Сегодня столкнулся с новой, интересной задачкой:

**Есть три сущности:**
```php

/** @ORM\Entity */
class User {
    ...
}

/** @ORM\Entity */
class Model extends User {
    ...
}

/** @ORM\Entity */
class Studio extends User {
    ...
}
```

Допустим мне необходимо `User` конвертировать в `Model`. Самый простой способ сделать это, грубо говоря, указать нужный тип `$user->_type = 'Model'`. Но как только мы хотим сделать `Model -> Studio`, то этот способ уже не прокатит, т.к. mapper вручную `_type` переопределит. Полагаю единтсвенный способ сделать это - переопределить mapper и в нем этот функционал выпилить.

По мне идеальным решением было бы иметь некий хелпер, который бы мог заниматсья конвертаций, типа переброски всех полей из одного объекта в другой и при этом корректировать Identity map, чтобы в момент persist'a объект сохранялся в базу как новая сущность.

**Comment by wolfy-j** [comment]
А ты не смотрел Heap и Nodels? Там можно смотреть на типы нод и контролировать все метаданные от которых зависит маппер. Если нужно делать страшную магию типа переноса одного домена в другой то можно сделать копирование контента ноды, но с другой ролью.

**Comment by wolfy-j** [comment]
Там нельзя сейчас поменять Node->role в рантайме, но переопределить хип можно, либо можно прокинуть через State...

**Comment by wolfy-j** [comment]
Но вообще я думаю можно просто подменить ноду, главное связи при пересоздании протащить.

**Comment by butschster** [comment]
> А ты не смотрел Heap и Nodes? Там можно смотреть на типы нод и контролировать все метаданные от которых зависит маппер. Если нужно делать страшную магию типа переноса одного домена в другой то можно сделать копирование контента ноды, но с другой ролью.

Ну ноду подменить это не самая большая проблема, это я в самом начале научился. 
А вот простого способа конвертации `Model` в `Studio` нет.

Пришлось написать что-то вроде:

```php
$mapper = $this->orm->getMapper($user);
$role = $mapper->getRole();

$model = (new \ReflectionClass(Model::class))->newInstanceWithoutConstructor();
$data = $mapper->extract($user);
$mapper->hydrate($entity, $data);

$heap = $this->orm->getHeap();

$heap ->detach($user);

$heap ->attach(
    $model,
    new Node(Node::MANAGED, $data, $role),
    $this->orm->getIndexes($role)
);
```

Вот что-то такое можно было бы для STI втащить, чтобы из коробки производить конвертации

_Кстати, вот чего действительно не хватает это публичного `getIndexes` в ORM. _

**Comment by butschster** [comment]
**Небольшое дополнение по способоу описанному в прошлом шаге:**
Все загруженные объекты в Identity map, у которых дананя сущность является связанной необходимо сохранять не каскадном режиме!

**Comment by wolfy-j** [comment]
Закинь пожалуйста тикет на getIndexes если он еще нужен.

**Comment by butschster** [comment]
> Сбрасываются связи? Их тоже нужно копировать.

Я бы сказал связи с данной сущностью у других загруженных сущностей ссылаются на старый объект

**Comment by wolfy-j** [comment]
А у тебя есть ревес связи?
