### ISSUE TITLE
Использование PostgreSQL типа array

### ISSUE THREAD

**Issue by butschster** [cycle/orm#103]
В PostgreSQL можно использовать поля для хранения массивов https://www.postgresql.org/docs/9.1/arrays.html
В документации не нашел информации по добавлению кастомных типов полей, поэтому хотел быт уточнить, какие есть способоы добавления новых типов?

**Comment by wolfy-j** [comment]
На текущий момент нет ограничений на кастомные типы, однако есть ограничение на что умеют встроенные миграции. Посмотри пример с UUID в документации, там показано как можно читать и писать типы напрямую. Однако, схему _пока что_ придется описать вне миграций (пока не добавим туда возможность описывать кастомные типы по простому).

**Comment by butschster** [comment]
В общем, насколько я понял, нет простого способа добавить поддержку `string[]`. У меня основная задача была искать по полю в БД на то, что массив в поле содержит значение. Я решил пойти немного по другому пути и поменять тип на `jsonb`, и в этом случае синтаксис выглядит как то так

```sql
select * from users where banned_countries ? 'RU';
```
Но столкнулся с тем, что такой запрос также нельзя выполнить, т.е. я не нашел способа как правильно его составить.

```php
$select->where(new Fragment('banned_countries ? "RU"'));
// Spiral\Database\Exception\StatementException : 
// SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "$1"
// LINE 9: WHERE banned_countries $1 "RU"

$select->where('banned_countries', '?', 'RU');
$select->where('banned_countries', '?', new Parameter('RU'));
// WHERE "user"."banned_countries" 'RU' ? 
// Spiral\Database\Exception\StatementException : 
// SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "$1"
// LINE 9: WHERE "user"."banned_countries" $1 $2
```

Такое ощущение что он постоянно ждет подставновки `?` на значение.

**Comment by wolfy-j** [comment]
Хмм, а ? это официальный синтаксис для таких запросов в PgSQL? Это странно ибо он серьезно конфликтует с PREPARE STATEMENT.

**Comment by wolfy-j** [comment]
Это можно обойти в теории на уровне компилятора, но я первый раз вижу ? вне подстановок.

**Comment by wolfy-j** [comment]
https://www.postgresql.org/docs/9.1/arrays.html#:~:text=8.14.-,Arrays,domains%20are%20not%20yet%20supported. 
https://www.postgresql.org/docs/9.4/functions-json.html

Я не вижу тут примеров с ?

**Comment by andrew-demb** [comment]
> Конфликтует с prepared statement
С 7.4 версии есть возможность экранировать `?` и использовать в запросах, не конфликтуя
https://wiki.php.net/rfc/pdo_escape_placeholders

**Comment by butschster** [comment]
https://www.postgresql.org/docs/9.4/functions-json.html Table 9-41.
Вот пример со stackoverflow - https://stackoverflow.com/questions/19925641/check-if-a-postgres-json-array-contains-a-string

**Comment by butschster** [comment]
> > Конфликтует с prepared statement
> 
> С 7.4 версии есть возможность экранировать `?` и использовать в запросах, не конфликтуя
> https://wiki.php.net/rfc/pdo_escape_placeholders

О, а вот это помогло, спасибо, не знал.

В общем итоговый запрос получился таким (Для вариант с использованием NOT лучше не придумал):
```php
$select->where(
    new Fragment('NOT("user"."stream_banned_countries" ?? \''.$country.'\')')
)
```

**Comment by wolfy-j** [comment]
можно сделать `new Expression('NOT(user.banned_countries ?? ?', $country)`

**Comment by wolfy-j** [comment]
в Expression можно внедрять значения, потом сделаем чтобы в Fragment тоже можно было
