### ISSUE TITLE
Cycle doesn't update nullable fields with 0 and vise versa

### ISSUE THREAD

**Issue by bjuri** [cycle/orm#108]
We have an entity
```php
/**
 * @Cycle\Entity()
 */
class Entity
{
    /**
     * @Cycle\Column(type="decimal(5,2)", nullable=true)
     * @var float|null
     */
    public $floatField;
}
```
And related value in DB:
`float_field: null`

When we tried to update this one with 0 value:
```php
$entity = $orm->getRepository(Entity::class)->findByPK(1);
$entity->floatField = 0;
$transaction->persist($entity);
$transaction->run();
```

Value of the updated row still didn't change and remain null value.

Same issue raises when we have 0 value saved in DB, and try to save null value

**Comment by wolfy-j** [comment]
Fixed in 1.2.11
