### ISSUE TITLE
Логирование запросов

### ISSUE THREAD

**Issue by butschster** [cycle/orm#110]
Начал изучать вопрос логирования запросов и столкнулся с интересной проблемой.

Согласно документации я могу включить логирование таким образом
```php
$driver = $dbal->database('default')->getDriver();
$driver->setLogger($myLogger);
```
Но этот способ немного сложный и его сложно применить глобально.

Я вижу, что `Spiral\Database\DatabaseManager` имеет метод `setLogger`, который по сути передает инстанс LoggerInterface в нужный Driver, но! Везде есть нюансы :+1: 

Открываем код:
```php
protected function getLogger(string $channel = null): LoggerInterface
    {
        if ($channel !== null) {
            return $this->allocateLogger($channel);
        }

        if ($this->logger !== null) {
            return $this->logger;
        }

        //We are using class name as log channel (name) by default
        return $this->logger = $this->allocateLogger(static::class);
    }
```

И видим, что даже имея установленный логер мы к нему никогда не доберемся, т.к. при выполнении запросов всегда передается `$channel` и нам нужно обязательно тянуть еще одну зависимость `ContainerScope`, а без нее нам всегда принудительно отдается `NullLogger`

```php
private function allocateLogger(string $channel): LoggerInterface
    {
        $container = ContainerScope::getContainer();

        if (empty($container) || !$container->has(LogsInterface::class)) {
            return new NullLogger();
        }

        //We are using class name as log channel (name) by default
        return $container->get(LogsInterface::class)->getLogger($channel);
    }
```

Предлагаю компромисс:
```php
return $this->logger ?: new NullLogger();
```

**Comment by wolfy-j** [comment]
O_o это больше похоже на багу

**Comment by wolfy-j** [comment]
А стоп, он форсирует только в случае если явно указан канал. По умолчанию он будет брать уже закешированный логгер.

**Comment by wolfy-j** [comment]
Можешь кинуть ПР сюда? https://github.com/spiral/logger/blob/master/src/Traits/LoggerTrait.php

**Comment by butschster** [comment]
> Можешь кинуть ПР сюда? https://github.com/spiral/logger/blob/master/src/Traits/LoggerTrait.php
Окей
