### ISSUE TITLE
Вопрос: есть ли Custom Mapping Types?

### ISSUE THREAD

**Issue by spvcoder** [cycle/orm#112]
Есть ли функционал похожий на Custom Mapping Types в Doctrine. Например, есть поле phone и в базе надо хранить значение в текстовом виде, а в коде использовать его как объект.

https://www.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/custom-mapping-types.html#custom-mapping-types

И использвать вот так:
```php
/** @Entity */
class User
{
    /** @Column(type = "primary") */
    protected $id;

    /** @Column(type = "phone") */
    protected $phone;
}
```

**Comment by rauanmayemir** [comment]
@spvcoder Вот же ж: https://cycle-orm.dev/docs/advanced-column-wrappers

**Comment by spvcoder** [comment]
Если я правильно понял, это именно обёртка над каким-то значением, получается в вашем примере я должен $value поместить внутрь другого объекта (column wrapper). Но это не то, что мне нужно.

Вот что я хотел: 

```php
$u = new User();
$u->phone = new MyPhoneObject('+122344556'); 
```

Тут я не хочу использовать обёртку, а хочу чтобы этот объект (MyPhoneObject) автоматом конвертировался в строку при вставке в базу.

Если это делать в доктрине, то:

```php
public function convertToDatabaseValue($value, AbstractPlatform $platform)
{
     return $value->toString(); //  - это будет мой объект MyPhoneObject
}
```

```php
public function convertToPHPValue($value, AbstractPlatform $platform)
{
        return new MyPhoneObject($value);
}
```

и на выходе я получаю этот же объект без обёрток. Можно ли такое как-то сделать в Cycle ORM?

**Comment by wolfy-j** [comment]
Если просто в базу то:
1) __toString(); это дефолтный фаллбек
2) https://github.com/spiral/database/blob/master/src/Injection/ValueInterface.php

Распаковывать можно через тайпкаст.
