### ISSUE TITLE
Проблема с выполнением миграций

### ISSUE THREAD

**Issue by butschster** [cycle/orm#114]
Привет!

Сегодня столкнулся с такой проблемой:

Есть несколько сущностей
```
Entities
-- Order
    -- Status.php
-- Order.php
```

Сущность Status.php имеет belongsTo связь с Order.php и при создании миграций схема для Status генерируется раньше чем Order и миграция падает из-за того, что внешние ключи не могут найти таблицу orders.

Пока я вижу только один вариант - Переименовать Status в OrderStatus и вынести из папки Order, но может есть еще какие либо варианты? Составлять схему вручную в конфиге наверно будет не лучшее предложение, мы пользуемся аннотациями.

**Comment by wolfy-j** [comment]
Эммм, миграции должны генерировать в порядке зависимостей моделей. Не по имени моделей. Однако учитывая что миграции запекают граф, в них есть ограничения. 

Если миграции ведут себя не ОК в случае сложных связей, то попробуй сначала сделать мигарации без связи, а потом с ней. Будет в два этапа и корректно. 

Багу проверим.

**Comment by butschster** [comment]
> Эммм, миграции должны генерировать в порядке зависимостей моделей. Не по имени моделей. Однако учитывая что миграции запекают граф, в них есть ограничения.
> 
> Если миграции ведут себя не ОК в случае сложных связей, то попробуй сначала сделать мигарации без связи, а потом с ней. Будет в два этапа и корректно.
> 
> Багу проверим.

Да, я только что поизучал процесс и вижу, что расположение в миграции не зависит от положения файла. Поэтому я поэкперементировал и нашел проблемное место

```php
/** @ORM\Entity() */
class Order {
    /** @ORM\Relation\RefersTo(target="Status") */
    private Status $status;
}

class Status {
     /** @ORM\Relation\BelongsTo(target="Order") */
    protected Order $order;
}
```

**Comment by wolfy-j** [comment]
RefersTo не являеется обратно связью BelongsTo, тут создалась циклическая зависимость. Попробуй HasOne (обратная BelongsTo).

**Comment by butschster** [comment]
> RefersTo не являеется обратно связью BelongsTo, тут создалась циклическая зависимость. Попробуй HasOne (обратная BelongsTo).

`$status` хранит текущий статус. Короче получается, что такую зависимость разрулить не получится. 

Есть только идея внешние ключи в миграциях создавать в самом конце. Т.е. сначала все таблицы с полями, а на последок уже запускать внешние ключи.

**Comment by wolfy-j** [comment]
Так все верно, Order hasOne Status. RefersTo это ссылочная связь, по типу BelongsTo.

**Comment by wolfy-j** [comment]
Order hasOne Status, Status belongsTo Order.

**Comment by butschster** [comment]
> Order hasOne Status, Status belongsTo Order. Они даже ключи одинаковые нагенерят :)

Order hasOne Status это ссылка на запись в таблице statuses, а мы хотели именно хранить последний статус в Order.

**Comment by wolfy-j** [comment]
А, ну тогда нужно создавать в два этапа либо писать миграцию руками. Миграции этого пока не умеют (cycle:sync умеет). Сама ОРМ конечно умеет, только убедитесь что дефолтные ключи не пересекаются, т.е. лучше сделать lastStatus
