### ISSUE TITLE
Merge STI relations when loading parent entity

### ISSUE THREAD

**Issue by armpogart** [cycle/orm#116]
As Single Table Inheritance is already supported (with some limitations), are there any plans to support Class Table Inheritance?

**Comment by wolfy-j** [comment]
I think you can already do that with HasOne and STI. Can you provide concrete use-case we can brainstorm it better?

**Comment by armpogart** [comment]
Here is an example of documentation for STI:

```php
/** @Entity */
class Post
{
    /** @Column(type="primary") */
    public $id;
}

/** @Entity */
class Article extends Post
{
    /** @Column(type="string") */
    public $articleTitle;
}
```
Both entities are stored in one table. Now for Class Table Inheritance I want `Article` entity to be stored in a separate table and still inherit shared properties/fields from parent. I have tried your suggestion:
```php
class Post
{
    /** @Column(type="primary") */
    public $id;

    /** @HasOne(target="Article", nullable=true) */
    public ?Article $article;
}

/** @Entity */
class Article extends Post
{
    /** @Column(type="string") */
    public $articleTitle;

    /** @BelongsTo(target="Post") */
    public Post $post;
}
```
and as you can see, I've even tried adding `BelongsTo` to the child entity, but they is only one table created still (the same on, as in STI case).
Also `Post` entity must not declare it's childs, such things must be possible without any knowledge of its' childs by parent entity as parent can have any number of childs.

One

**Comment by wolfy-j** [comment]
You can def do that directly in the schema by simply assigning them different tables. I assume we can treat these entities separate IF you'll declare different tables in them. @Entity(table="articles"). We can add it into schema builder but it will require PR or some time for our team.

But with manual schema declaration this is def possible.

**Comment by armpogart** [comment]
@wolfy-j Ok, I'll try to see how it can be done and prepare PR.

**Comment by armpogart** [comment]
@wolfy-j I see how I can force schema builder to treat it as separate entity in case if they have different table definitions, but would it be possible to force the `Article` entity to load/write it's parent fields (when reading and then when writing) to `Post` entities table? Where do I look/make changes for that?

**Comment by wolfy-j** [comment]
Using custom mapper - sure. You can easily send multiple commands to multiple tables, see the example: 
https://github.com/cycle/docs/blob/master/advanced/custom-mapper.md

If won't work out of the box but you can create your own mapper:

- implement Article->Post relation as hasOne + eager load
- custom hydrate method which merges `data` and `data[post]` to single array
- custom extract method which filters article related columns
- alter scheduleUpdate, scheduleCreate method to attach command to store record in Post table, OR relation handler

I need to think about how to make it easier in the future.

**Comment by armpogart** [comment]
In that case custom mapper must be also in the core library (I mean crm), if you are going to support this out of box, but the problem I see in that case, is that in case if someone wants to define a custom mapper for the child, it will overwrite the one already there for the right mapping.

I have made all the modifications necessary to `schema-builder` (taking into account that we don't need also to join parent fields in that case), will open PR for that there, and will look on implementing custom mapper now. Though I think the right solution would be to have additional annotation ([as it is in Doctrine](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/inheritance-mapping.html)) for this to detect the case easier and use the mapper in any case, or somehow merge the mapper with the custom one defined by the user.

P.S. I don't have full picture how cycle works under the hood, so I'm just speculating on what I see and know already and am not pretending on building good solution without digging into the code more, so I will just do what I can now.

**Comment by armpogart** [comment]
@wolfy-j I have actually made the necessary changes to `cycle/annotated` instead of `schema-builder` (see linked PR). Is this right approach?

**Comment by wolfy-j** [comment]
I see your approach and yes, it will work. Essentially it's the same I propose with manual schema definition. We need tests for it thought.

**Comment by guilhermeaiolfi** [comment]
I would like to discuss it further here. I get it working using the custom mapper approach. But I think we would need to think in a different Schema definition for this use case and maybe incorporate that behavior in the default mapper. I was maybe thinking in introducing Schema::PARENT_ROLE. That would add the HAS_ONE relation and extract the fields from that relation to the root entity and deal with updating, deleting entries.

Coming from doctrine, one question that remains is how to treat selections.  In doctrine it would load the right data even for a colletion/selection. I don't know how to do it, even using custom mappers. Because left joining the data and hydrating depending on the type would need a totally different approach from the ones we already have in Cycle, right?

**Comment by wolfy-j** [comment]
> Coming from doctrine, one question that remains is how to treat selections. In doctrine it would load the right data even for a colletion/selection. I don't know how to do it, even using custom mappers. Because left joining the data and hydrating depending on the type would need a totally different approach from the ones we already have in Cycle, right?

Can you elaborate? Currently, mapper knows all the child types and able to select the proper class with proper hydration in initEntity method.

**Comment by guilhermeaiolfi** [comment]
> Can you elaborate? Currently, mapper knows all the child types and able to select the proper class with proper hydration in initEntity method.

If I have:
```
User (id, name)
Customer extends User(email)
Admin extends User (permissions)
```

When constructing a query for any kind of User like: ```$select->fetchAll()```, it will need to left join the email and permissions from the related children tables to get `email` and `permissions`. So the following would be possible:

```php
foreach ($users as $u) {
    if (get_class($u) == Customer::class) {
        echo $u->email;
    } else if (get_class($u) == Admin::class) {
       echo $u->permissions;
    }
}
```

Currently the STI does that, because all columns are in the same table. But when using children tables to hold the extra information, you'll need to left join the data or you'll end up with N+1 situations if lazy loading them. 

Actually, I don't know how doctrine does that. Cycle could POST LOAD those relations, maybe. That would be nice too.

**Comment by wolfy-j** [comment]
Got it. It should be possible but it will require some sort of relation merge to single selection. Interesting edge case.

**Comment by guilhermeaiolfi** [comment]
hi,

I am trying to implement the last item described here:

> * implement Article->Post relation as hasOne + eager load
> * custom hydrate method which merges `data` and `data[post]` to single array
> * custom extract method which filters article related columns
> * alter scheduleUpdate, scheduleCreate method to attach command to store record in Post table, OR relation handler

I manage to come up with:

```php
public function queueUpdate($entity, Node $node, State $state): ContextCarrierInterface
    {
        $parentRole = "page";
        $cmd = parent::queueUpdate($entity, $node, $state);

        $cs = new ContextSequence();
        $cs->addPrimary($cmd);

        $data = $this->fetchFields($entity);
        $parentEntity = $node->getRelation($parentRole);
        $parentNode = $this->orm->getHeap()->get($parentEntity);


        $changes = array_udiff_assoc($this->extractParentEntity($entity), $parentNode->getState()->getData(), [Node::class, 'compare']);

        $parentPrimaryKey = $this->orm->getSchema()->define($parentRole, Schema::PRIMARY_KEY);
        $parentColumns = $this->orm->getSchema()->define($parentRole, Schema::COLUMNS);
        $parentSource = $this->orm->getSource($parentRole);
        $parentPrimaryColumn = $parentColumns[$parentPrimaryKey] ?? $parentPrimaryKey;
        unset($changes[$parentPrimaryKey]);

        $changedColumns = [];
        foreach ($changes as $column => $value) {
            $changedColumns[$parentColumns[$column] ?? $column] = $value;
        }

        $parentUpdate = new Update($parentSource->getDatabase(), $parentSource->getTable(), $changedColumns);
        $cs->addCommand($parentUpdate);

        $parentNode->getState()->forward(
            $parentPrimaryKey,
            $parentUpdate,
            $parentPrimaryColumn,
            true,
            ConsumerInterface::SCOPE
        );

        return $cs;
    }
```
I hope the code is self explanatory. It is working, but I pretty sure I am mixing up some things here and probably it it is doing more than it should. So, before I go any further to implement the `queueCreate`, is there something obviously wrong any of you guys could point me out?

For others in the same situation: I had to set `Relation::CASCADE           => false,` in the children nodes, otherwise it would remove the parent record when trying to update.

**Comment by guilhermeaiolfi** [comment]
```php
public function queueCreate($entity, Node $node, State $state): ContextCarrierInterface
    {
        $parentRole = "page";
        $columns = $this->extractParentEntity($entity);
        $parentEntity = $this->orm->make($parentRole, $columns);
        $entity->page = $parentEntity;
        $insert = parent::queueCreate($entity, $node, $state);

        $cs = new ContextSequence();

        $parentPrimaryKey = $this->orm->getSchema()->define($parentRole, Schema::PRIMARY_KEY);
        $parentColumns = $this->orm->getSchema()->define($parentRole, Schema::COLUMNS);

        $columns = $this->extractParentEntity($entity);
        $data = [];
        foreach ($columns as $column => $value) {
            $data[$parentColumns[$column] ?? $column] = $value;
        }
        $parentNode = $this->orm->getHeap()->get($parentEntity);
        $parentMapper = $this->orm->getMapper($parentRole);
        $parentState = $parentNode->getState();

        $parentSource = $this->orm->getSource($parentRole);
        $parentPrimaryColumn = $parentColumns[$parentPrimaryKey] ?? $parentPrimaryKey;

        // sync the state
        $parentState->setStatus(Node::SCHEDULED_INSERT);
        $parentState->setData($columns);

        $columns[$parentPrimaryKey] = $columns[$parentPrimaryKey] ?? $parentMapper->nextPrimaryKey();
        if ($columns[$parentPrimaryKey] === null) {
            unset($columns[$parentPrimaryKey]);
        }


        $parentInsert = new Insert(
            $parentSource->getDatabase(),
            $parentSource->getTable(),
            $data,
            $parentPrimaryColumn
        );
        $cs->addPrimary($parentInsert);

        $cs->addCommand($insert);

        $key = isset($columns[$parentPrimaryKey]) ? $parentPrimaryKey : Insert::INSERT_ID;


        $insert->waitContext($this->primaryKey, true);

        $parentInsert->forward($key, $insert, $this->primaryKey);

        return $cs;
    }
```

That kinda of worked too, in the sense that the two inserts are being execute and the right ID defined. But somehow in the middle of it, `CommandGenerator` calls `queueUpdate` and the `$node` there loses its relationship to the parent node, so: 

`$node->getRelation($parentRole); // returns NULL.`
