### ISSUE TITLE
SELECT DISTINCT ON (city_name) city_name, time_zone FROM cities

### ISSUE THREAD

**Issue by rumatakira** [cycle/orm#118]
Is it possible to implement with ORM?

**Comment by wolfy-j** [comment]
Yeah, `->distinct('city_name')`

**Comment by wolfy-j** [comment]
https://cycle-orm.dev/docs/query-builder-extended#selectquery-builder-groupby-and-distinct

**Comment by wolfy-j** [comment]
Note, not all DBs support expression distinct.

**Comment by rumatakira** [comment]
`$result = $database->table('cities')->select()->distinct('city_name')->columns('city_name', 'time_zone')->orderBy('city_name')->fetchAll();

response 200
{
    "city_name": "Moscow",
    "time_zone": "Europe\/Berlin"
  },
  {
    "city_name": "Moscow",
    "time_zone": "Europe\/Moscow"
  },

**Comment by rumatakira** [comment]
$result = $database->query('SELECT DISTINCT ON (city_name) city_name, time_zone FROM cities ORDER BY city_name')->fetchAll();

response 200
{
    "city_name": "Moscow",
    "time_zone": "Europe\/Moscow"
  },

**Comment by wolfy-j** [comment]
Hmmm

**Comment by wolfy-j** [comment]
What Database do you use?

**Comment by wolfy-j** [comment]
@rumatakira can you please provide spiral/database version number and database driver you use.

**Comment by rumatakira** [comment]
PostgreSQL 12.3
spiral/database  v2.7.15
Spiral\Database\Driver\Postgres\PostgresDriver

**Comment by wolfy-j** [comment]
Hi,

apparently `distinct` and `distinct on` are very different operations on PostgreSQL which does not have analogue in other databases. 

We can introduce new method `distinctOn` for Postgres driver only. Would that work for you?

**Comment by rumatakira** [comment]
Super! U r really the best people!

**Comment by wolfy-j** [comment]
Added in dbal v2.7.17
