### ISSUE TITLE
Persisting immutable entities

### ISSUE THREAD

**Issue by armpogart** [cycle/orm#119]
Is it possible somehow to persist immutable entities?
I mean if I have immutable entities in my application, and I need to change it (update some property), I create a new entity with the same PK, and now I want to persist it, but ORM sees it as a new entity and encounters conflict (duplicate PK) while trying to save the entity.
I realize that we need a way to distinguish between new entity with conflicting key and updated one in that case, and relying only on PK is not a way to go. But is there a way I can define when 2 entities are the same (maybe by using some internal object hash) and make the heap rely on it, instead of object reference?

Or maybe we can add an interface, and the entities implementing that interface will define whether they are equal to other object or not, similar to equality operator overloading in other languages or [IEquatable](https://docs.microsoft.com/en-us/dotnet/api/system.iequatable-1?view=netcore-3.1) interface in .Net.

**Comment by rauanmayemir** [comment]
@armpogart I had a similar use case where I had two keys - one for PK, another one for root id. (so updating would require unsetting the PK and thus forcing the ORM to insert the entity as new)
Check out this repo to get the idea on a possible approach: https://github.com/wolfy-j/spiral-versioned-mapper-repro

**Comment by wolfy-j** [comment]
Try to register new entity in Heat using same (not sure) or copied Node with state MANAGED. https://github.com/cycle/docs/blob/master/advanced/entity.md
