### ISSUE TITLE
Different values returned from the same operation

### ISSUE THREAD

**Issue by rumatakira** [cycle/orm#121]
```
// by ORM tools

                $insert = $this->database->insert('divisions');
                $insert->values([
                    'division_name' => $divisionName,
                    'division_address' => $divisionAddress,
                    'division_coordinates' => $divisionCoordinates,
                    'division_type' => $divisionType,
                    'company_id' => $divisionCompanyId]);
                dd($insert->run());
```
returns: 27

```
// raw SQL

$id = $this->database->query("INSERT INTO divisions (division_name, division_address, division_coordinates, division_type, company_id) VALUES (?,?,?,?,?)", [$divisionName, $divisionAddress, $divisionCoordinates, $divisionType, $divisionCompanyId]);
```

returns: 
^ Spiral\Database\Driver\Statement {#19724 ▼
  -pdoStatement: PDOStatement {#17113 ▼
    +queryString: "INSERT INTO divisions (division_name, division_address, division_coordinates, division_type, company_id) VALUES (?,?,?,?,?)"
  }
}

PG 12.4
spiral/database v2.7.16

**Comment by wolfy-j** [comment]
If you want to use raw queries make sure to call lastInsertId(). The database does not know what type of query you inserted into `query`. I would also recommend using `execute` not query.

**Comment by wolfy-j** [comment]
`database->insert` relies on query builder which also simplifies access to `lastInsertId`.

**Comment by rumatakira** [comment]
it looks like lastInsertID, not lastInsertId  - from https://github.com/spiral/database/blob/master/src/Driver/Driver.php
```/**
     * Get id of last inserted row, this method must be called after insert query. Attention,
     * such functionality may not work in some DBMS property (Postgres).
     *
     * @param string|null $sequence Name of the sequence object from which the ID should be returned.
     * @return mixed
     */
    public function lastInsertID(string $sequence = null)
    {
        $result = $this->getPDO()->lastInsertId();
        if ($this->logger !== null) {
            $this->logger->debug("Insert ID: {$result}");
        }

        return $result;
    }
```

but I can not call this method from Cycle ORM

**Comment by wolfy-j** [comment]
You don’t need to call it from Cycle since it will hydrate PK automatically. Can you describe your use case?

**Comment by rumatakira** [comment]
This is API educational task how to use bundle Roadrunner-Cycle ORM-PG instead of Nginx-Doctrine-PG. API generates from YAML swagger file to Slim4 stub. The condition was that all queries must have two versions - raw SQL and by Cycle ORM tools. But directly in that place of code I need the number of the row inserted to db. I have it by Cycle ORM layer, but can not recieve from DBAL layer of Cycle ORM. How can I do that?

**Comment by wolfy-j** [comment]
You can access the DBAL from ORM the following way:

```php
// cycle orm instance
$db= $orm->getFactory()->database(); // you can pass db name to this method if you use multiple sources
```

After that you can use the DBAL documentation: https://spiral.dev/docs/database-access
