### ISSUE TITLE
It doesn't load relation when filtering by column of junction table

### ISSUE THREAD

**Issue by guilhermeaiolfi** [cycle/orm#129]
For this schema:

```php
    'place' => [
        Schema::ROLE        => 'place',
        Schema::ENTITY      => StrClass::class,
        Schema::MAPPER      => StdMapper::class,
        Schema::DATABASE    => 'default',
        Schema::TABLE       => 'places',
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS     => [
            'id',
            'name'
        ],
        Schema::TYPECAST    => [
            "id" => "int"
        ],
        Schema::SCHEMA      => [],
        Schema::RELATIONS   => [
            'members' => [
                Relation::TYPE   => Relation::MANY_TO_MANY,
                Relation::TARGET => 'user',
                Relation::SCHEMA => [
                    Relation::CASCADE           => true,
                    Relation::THROUGH_ENTITY    => 'place_member',
                    Relation::INNER_KEY         => 'id',
                    Relation::OUTER_KEY         => 'id',
                    Relation::THROUGH_INNER_KEY => 'place_id',
                    Relation::THROUGH_OUTER_KEY => 'user_id'
                ]
            ]
        ]
    ],
    'place_member' => [
        Schema::ROLE        => 'place_member',
        Schema::ENTITY      => StrClass::class,
        Schema::MAPPER      => StdMapper::class,
        Schema::DATABASE    => 'default',
        Schema::TABLE       => 'place_members',
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS     => [
            'id',
            'user_id',
            'place_id',
            'role_id',
            'period_id'
        ],
        Schema::TYPECAST    => [
            "id" => "int",
            'user_id' => 'int',
            'place_id' => 'int',
            'period_id' => 'int',
            'role_id' => 'int'
        ],
        Schema::SCHEMA      => [],
        Schema::RELATIONS   => [
            'role' => [
                Relation::TYPE   => Relation::BELONGS_TO,
                Relation::TARGET => 'roles',
                Relation::SCHEMA => [
                    RELATION::NULLABLE => true,
                    Relation::CASCADE   => true,
                    Relation::INNER_KEY => 'role_id',
                    Relation::OUTER_KEY => 'id'
                ]
            ]
        ]
    ]
]
```

When I run this query:
```php
    $place = $cycle
        ->getRepository('place')
        ->select()
        ->load([
            'members' => [ 'as' => 'membersOfThatPeriod', 'where' => [ '@.@.period_id' => 2 ]], 
            'membersOfThatPeriod.@.role' 
        ])
        ->wherePk(1)
        ->fetchData());
```

```php
echo $place->members->getPivot($place->members[0])->role; // NULL <--- WRONG!
```

I know that the schema is OK, because if I remove the `membersOfThatPeriod.@.role` from the query, it gives me a reference to 'role' with the right ```id```. And doing something like:

```php
$item = $cycle->>getRepository('place_member')->select()->load('role')->fetchOne(); 
echo $item->role->name; // display the name of that role corretly.
```

* Looking at the generated queries, the table `roles` was never used in any of them.

**Comment by guilhermeaiolfi** [comment]
Actually, my description was wrong. I am trying to found the problem while understading how cycle works. The problem is not actually because of the filter. Something like the following wouldn't work either:
```php
$load('members.@.role');
```

Since there is a test for that same use case (https://github.com/cycle/orm/blob/e19e50bf39af3da9651443f60b87837404224321/tests/ORM/ManyToManyDeepenedTest.php) I discover that the problem is in the BELONGS_TO relationship. Changing it to HAS_ONE worked. But `roles` is not an exclusive relationship, so that won't work for me.

**Comment by wolfy-j** [comment]
Have you tried HAS_MANY? belongs to relies on FK value from source table, HasOne from the foreign table, so they are inverted versions of each other. The default load method is irrelevant here as it a common optimization, you can use any method with each of this relations.

**Comment by guilhermeaiolfi** [comment]
I think I missing something here. I am not using annotations. So, there is no `inverse` option, right? I don't see how using the HAS_MANY in the target table will handle that case. I need a path from that junction table to the next. Not the other way around. 

> The default load method is irrelevant here as it a common optimization, you can use any method with each of this relations.

Yes,  I know I can change it. I am using the `method` to make it work now. But since the default one doesn't work in those case, it shouldn't be as other can face the same problem and there is no errors, warnings, to help them know what is going on.

**Comment by guilhermeaiolfi** [comment]
ok, be patience with me 😄 What I really wanted was the REFERS_TO relation. Since neither side has an exclusive relationship to each other. 

Still, the problem here is the POSTLOAD method, since it won't load any data and I am pretty sure it is a bug.

To illustrate what I am saying, change this line: https://github.com/cycle/orm/blob/e19e50bf39af3da9651443f60b87837404224321/tests/ORM/ManyToManyDeepenedTest.php#L242

TO: 
```php
->load('tags.@.image', ['method' => => Select\JoinableLoader::POSTLOAD])
```
The tests won't pass:
```php
--- Expected
+++ Actual
@@ @@
                 'user_id' => 1
                 'tag_id' => 1
                 'as' => 'primary'
-                'image' => Array &4 (
+                'image' => null
+                '@' => Array &4 (
                     'id' => 1
-                    'url' => 'first.jpg'
-                    'parent_id' => 1
-                )
-                '@' => Array &5 (
-                    'id' => 1
                     'name' => 'tag a'
                 )
             )
-            1 => Array &6 (
+            1 => Array &5 (
                 'id' => 2
                 'user_id' => 1
                 'tag_id' => 2
                 'as' => 'secondary'
                 'image' => null
-                '@' => Array &7 (
+                '@' => Array &6 (
                     'id' => 2
                     'name' => 'tag b'
                 )
@@ @@
             )
         )
     )
-    1 => Array &8 (
+    1 => Array &7 (
         'id' => 2
         'email' => 'another@world.com'
         'balance' => 200.0
-        'tags' => Array &9 (
-            0 => Array &10 (
+        'tags' => Array &8 (
+            0 => Array &9 (
                 'id' => 3
                 'user_id' => 2
                 'tag_id' => 3
                 'as' => 'primary'
-                'image' => Array &11 (
-                    'id' => 2
-                    'url' => 'second.png'
-                    'parent_id' => 3
-                )
-                '@' => Array &12 (
+                'image' => null
+                '@' => Array &10 (
                     'id' => 3
                     'name' => 'tag c'
                 )
```


As you can see, "image" is now ```null```.

**Comment by wolfy-j** [comment]
I would really appreciate it if you can create PR with such test, it will drastically speed up the fix. You can create a new test if needed, use php `tests/generate.php` to create new test suite.

I think it's a MtM limitations, but I have to see it in place. Sorry for kicking it back to you, we are seriosly busy with upcoming and very massive component.

**Comment by wolfy-j** [comment]
Ok, the fix was pretty obvious. We did not resolve pivotedLoaded in many to many and all POSTLOADS was ignored. I've added test and fix for it in v2.1.13

https://github.com/cycle/orm/commit/bf7d159ba629047a33038ab39c6dc0af16a1c415

**Comment by wolfy-j** [comment]
I'll release update once tests pass.

**Comment by guilhermeaiolfi** [comment]
I've just test your fix and it worked. Thank you so much. You are the man!!!
