### ISSUE TITLE
References in the heap prevent objects to load correctly

### ISSUE THREAD

**Issue by guilhermeaiolfi** [cycle/orm#133]
Hi,

as discussed in discord, when using something like:
```php
$obj->organization = new Reference('organization', ['id' => 1]);
$tr->persist($obj);
$tr->run();
```
and after in the same request doing:
```php
$obj = $select->load('organization')->wherePk(2)->fetchOne();
```

`$obj->organization` is an instance of `Cycle\ORM\Promise\Reference`  instead of the entity instance. It can cause quite an unpredictable behavior that turn the use of references a challenge.

**Comment by wolfy-j** [comment]
Fixed in v1.3.3. Thank you!
