### ISSUE TITLE
Remove service container

### ISSUE THREAD

**Issue by root-aza** [cycle/orm#148]
Приветствую.Входи разработки интеграции cycle с sf заметил,что в фабрике orm инжектиться 2 контейнера,один используется,а второй нет. [Ссылка на код](https://github.com/cycle/orm/blob/master/src/Factory.php#L66)

[PR](https://github.com/cycle/orm/pull/147)

**Comment by wolfy-j** [comment]
Fixed in v1.3.3. Thank you!
