### ISSUE TITLE
Select won't load relations for object already in the heap

### ISSUE THREAD

**Issue by guilhermeaiolfi** [cycle/orm#150]
Hi,

kind of the same source of problem described here: https://github.com/cycle/orm/issues/133. Reusing the heap objects can lead to a very unpredictable results. Another one is the following:

```php
$cycle->getRepository('my_super_table')->select()->orderBy("id", "DESC")->fetchOne(); // returns id: 2, for example
// ... later on in the same request ...
$cycle->getRepository('my_super_table')->select()->load("relationOne", "relationTwo")"->fetchAll(); // collections contains id: 2
```

In that case, the objects that were already in the heap because of the first select won't have the relations loaded. But if I comment out the first select (the fetchOne()) it works correctly. 

As expected, if I clean the head using ```$cycle->getHeap()->clean();``` after the first select, it works too. But the more dynamically my code gets worst it gets and I am having to put a lot of extra heap cleaning up calls.

**Comment by wolfy-j** [comment]
Hi, the problem in such a case that the previous state of the relation will be erased. Including any modifications to collections and child relations. I think that we can implement it as part of the core. We will take care after dealing with another milestone. If you want to take a look by yourself:

https://github.com/cycle/orm/blob/master/src/ORM.php#L162

Also I can recommend to use ‘orm->withHeap()’ to create new scope for a better separation.

**Comment by wolfy-j** [comment]
Fixed in v1.3.3. Thank you!

**Comment by guilhermeaiolfi** [comment]
Thanks, @wolfy-j . Should that fix work for ```getRepository(*ANY*)->findByPK($id)``` too?

I tried removing the ```withHeap()``` workaround in my code in those cases and it won't update the relations.

**Comment by wolfy-j** [comment]
Yes, it should work for all the selections when data referenced from the same heap. If it does not - I need some way to recreate it.
