### ISSUE TITLE
Доработка документации

### ISSUE THREAD

**Issue by floor12** [cycle/orm#152]
Добрый день всем. 
Делал несколько подходов к этой ОРМ, но к сожалению, документация совершенно недостаточная в случае, когда необходимо замапить сущности, где много различных value-object и при этом,  сделать это все без аннотаций, а за счет создания своих классов-маперов, когда каждый вложенный объект хочется мапить и сериализовать в json по своему усмотрению.
Хотелось бы попросить дополнить документацию по мапингу с примерами сложных объктов, их связями и тд.

**Comment by floor12** [comment]
При этом, задача состоит в том, чтобы не только избежать аннотаций в классах, но и не засорять value-object статическим методом typecast.

То есть, хочется полностью доменную модель отделить от любых такого рода зависимостей, как будто она подключается в проект как отдельная либа.

**Comment by wolfy-j** [comment]
Это все делается через кастомные мапперы, надо подумать как упросить это.

**Comment by wolfy-j** [comment]
Т.е. какой-то "коробочный" способ конфигурации методов hydrate/extract в MapperInterface.

**Comment by floor12** [comment]
Спасибо за ответ!
Да, изучив чуток исходники, я это понял, и сделал свои классы-мапперы, переопределив методы hydrate/extract.
Сначала все пошло хорошо, объекты создавались и доставались из базы корректно. С проблемой я столкнулся, когда захотел объекты обновить. Не смотря на то, что определил какое поле является ключом, получаю ошибку отсутствия scope, то есть условия when. Где-то в недрах, орм не понимает какое условие надо поставить... с этим сейчас разбираюсь. Может там какие-то подводные камни есть? )

А что касается того, как проще организовать маппинг, можно использоваться анонимные функции (доработка примера из документации):

```php
   Schema::TABLE => 'user',
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',    // property => column
            'email' => 'email',
            'balance' => 'balance', //int
            'tags' => 'tags' // jsonb
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'balance' => function ($value) {
                new Balance($value);
            },
            'tags' => function ($value) {
                return array_map(function ($tag) {
                    return new Tag($tag);
                }, json_decode($value));
            },
        ],
        Schema::RELATIONS => []
```
