### ISSUE TITLE
Несоответствие названия колонки в таблице с названием поля в сущности

### ISSUE THREAD

**Issue by only-viktor** [cycle/orm#153]
Пример:

**Order.php:**
```
/**
 * @Cycle\Entity(
 *     role="custom_order"
 * )
 */
final class Order
{
    /**
     * @Cycle\Column(type="primary")
     */
    public ?int $id = null;

    /**
     * @Cycle\Relation\HasMany(target=OrderItem::class, cascade=true)
     */
    public Collection $items;

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }
}
```

**OrderItem.php:**
```
/**
 * @Cycle\Entity(
 *     role="custom_order_item"
 * )
 */
final class OrderItem
{
    /**
     * @Cycle\Column(type="primary")
     */
    public ?int $id = null;

    /**
     * @Cycle\Relation\BelongsTo(
     *     target=Order::class,
     *     inverse=@Cycle\Relation\Inverse(as="items", type="hasMany")
     * )
     */
    public ?Order $order = null;
}
```

Сгенерированная миграция для OrderItem выглядит так:

```
$this->table('custom_order_items')
            ->addColumn('id', 'primary', [
                'nullable' => false,
                'default'  => null
            ])
            ->addColumn('custom_order_id', 'integer', [
                'nullable' => false,
                'default'  => null
            ])
            ->addColumn('order_id', 'integer', [
                'nullable' => false,
                'default'  => null
            ])
            ->addIndex(["order_id"], [
                'name'   => 'custom_order_items_index_order_id_601006709bd12',
                'unique' => false
            ])
            ->addForeignKey(["order_id"], 'custom_orders', ["id"], [
                'name'   => 'custom_order_items_foreign_order_id_601006709bd74',
                'delete' => 'CASCADE',
                'update' => 'CASCADE'
            ])
            ->setPrimaryKeys(["id"])
            ->create();
```

Проблема в том что создается два ключа **custom_order_id** и **order_id**.
Проблему можно решить указав **outerKey="order_id"** в аннотациях для **Order::$items**
Хотелось бы решить проблему так, чтобы всегда формировалось имя ключа только по названию поля **$order** в сущности **OrderItem**, а не по названию роли **custom_order** в сущности **Order**.

**Comment by greabock** [comment]
Мне кажется, что проблема в inverse. Цитата из документации:

> In some cases you might want to create an inversed relation automatically.

Но на сущности `Order` и так уже определено отношение. Получается, что ORM думает, что это два разных отношения.

**Comment by only-viktor** [comment]
Предлагаю этот патч для решения.

[RelationOuterKey.patch.zip](https://github.com/cycle/orm/files/5879825/RelationOuterKey.patch.zip)

**Comment by roxblnfk** [comment]
> Мне кажется, что проблема в inverse. Цитата из документации:
> 
> > In some cases you might want to create an inversed relation automatically.
> 
> Но на сущности `Order` и так уже определено отношение. Получается, что схема ORM думает, что это два разных отношения.

`inverse` для `@BelongTO` в `OrderItem` следует использовать в том случае, когда отношение `@HasMany` не указано в `Order`.

Однако и без `@Inverse` в данном примере в `custom_order_item` будут два поля: `order_id` и `custom_order_id`.

Связано это вот с чем:

- `custom_order_id` генерирует связь `@HasMany` на основе **названия роли** родительского класса `Order` (role = `costom_order`)
- `order_id` генерируется в `@BelongTo` на основе **названия поля**, на котором висит `@BelongTo`. Т.е. `order`.

---

Чтобы исправить разницу в названиях ключей, достаточно либо переименовать поле `OrderItem::$order` в `OrderItem::$custom_order`,
либо явно указать inner/outer key:

* В `@BelongsTo` класса `OrderItem`:
  ```
       * @BelongsTo(
       *     target="custom_order",
       *     innerKey="custom_order_id"
       * )
      public ?Order $order = null;
  ```
* Или в `@HasMany` класса `Order`
  ```
      /**
       * @HasMany(target=OrderItem::class, cascade=true, outerKey="order_id")
       */
      public $items;
  ```
