### ISSUE TITLE
Detect tables that should be dropped on cycle:migrate

### ISSUE THREAD

**Issue by vladgorenkin** [cycle/orm#154]
Currently `cycle:migrate` does not detect unmanaged tables (after deleting entity file, schema is defined via annotations), so you have to append `drop` commands to migration file manually. Am I doing something wrong or is it expected behavior?

**Comment by wolfy-j** [comment]
This is expected behavior. It is recommended to add such table removals manually.

**Comment by vladgorenkin** [comment]
Got it, thanks
