### ISSUE TITLE
RefersTo with nullable=false can't persist related entities

### ISSUE THREAD

**Issue by Eugentis** [cycle/orm#183]
In case when you need to use relation `RefersTo` with `nullable=false` it was detected error in persist for several entities in one transaction.

**Example** for client address which should be reusable for many other entities:
```php
class Client {
    /**
     * @Cycle\Relation\RefersTo(target=Address::class, nullable=false, fkAction="NO ACTION")
     */
    public Address $address;
    ...
}
```

If you want to add client and address in one transaction you will hit with error like:
`SQLSTATE[HY000]: General error: 1364 Field 'address_id' doesn't have a default value...`

Transaction example code can be smth like:
```php
public function createClient(ClientRegRequest $request, TransactionInterface $transaction): Client
{
    $address = new Address($request->city, $request->street);
    $transaction->persist($adress);

    $client = new Client($request->email, $request->name, $address);
    $transaction->persist($client);

    $transaction->run();
}
```

**Note:** if you change RefersTo to BelongsTo it will solve the problem but it is not logical - client belongs to address...

**Comment by roxblnfk** [comment]
Relation `RefersTo` with `nullable=false` will be replaced with `BelongsTo` relation under the hood of ORM v2
