### ISSUE TITLE
Missing type casting call for primary key

### ISSUE THREAD

**Issue by roquie** [cycle/orm#203]
PHP Version: 8.0
Cycle ORM: 1.5.0

If you use the UUID as the primary key, then when fetching related records, the ORM crashes with an error:

```
[TypeError]
array_key_exists(): Argument #1 ($key) must be a valid offset type.
```

https://github.com/cycle/orm/blob/master/src/Parser/AbstractNode.php#L341 

How to reproduce:
1.  Follow this guide https://cycle-orm.dev/docs/advanced-column-wrappers 
2. Follow this guide https://cycle-orm.dev/docs/advanced-uuid (but don't forget to replace Ramsey UUID with a typecasted object from p.1 in `nextPrimaryKey`).

Possible fix:

```php
    protected function mountArray(string $container, string $key, $criteria, array &$data): void
    {
        $criteria = (string) $criteria; // fix

        if (!array_key_exists($criteria, $this->references[$key])) {
            throw new ParserException("Undefined reference `{$key}`.`{$criteria}`");
        }

        foreach ($this->references[$key][$criteria] as &$subset) {
            if (!in_array($data, $subset[$container], true)) {
                $subset[$container][] = &$data;
            }

            unset($subset);
            continue;
        }
    }
```

**Comment by roxblnfk** [comment]
It is correct fix. Would you like to create a PR?

**Comment by roxblnfk** [comment]
PR merged but still neet to add test case

**Comment by roxblnfk** [comment]
Outdated
