### ISSUE TITLE
Suggestion: Add typecasters

### ISSUE THREAD

**Issue by vjik** [cycle/orm#216]
```php
interface TypeCasterInterface
{
    public function convertToDatabaseValue(mixed $value): mixed;
    public function convertToEntityValue(mixed $value): mixed;
}
```

```php
Schema::TYPECAST => [
    'id' => 'int',
    'specificValue' => new MyCustomTypeCaster(),
],
```

When convert value from DB to entity run `TypeCasterInterface::convertToEntityValue()`.
When convert value from entity to DB run `TypeCasterInterface::convertToDatabaseValue()`.

Can create default typecasters (`IntTypeCaster` with alias `int`, `StringTypeCaster` with alias `string`, ...) and allow users create own typecasters.

In many cases, this will allow us not to use custom mappers.

For example, I can create in own project:

```php
final class DateTimeImmutableToIntegerType implements TypeCasterInterface
{
	public function convertToDatabaseValue(mixed $value): mixed {
		return $value === null ? null : (string)$value->getTimestamp();
	}
	
	public function convertToEntityValue(mixed $value): mixed {
		return $value === null ? null : (new DateTimeImmutable())->setTimestamp((int)$value);
	}
}
```

**Comment by roxblnfk** [comment]
This feature planned in the ORM v2

**Comment by roxblnfk** [comment]
Done https://github.com/cycle/orm/pull/236
