### ISSUE TITLE
Add support for composite PK and relations [9/16]

### ISSUE THREAD

**Issue by wolfy-j** [cycle/orm#22]
What is currently done:
- ability to generate schema with composite PK
- ability to persist entity with composite PK (PK generation is application layer specific)
- ability to request entity by composite key from Repository, ORM* and Heap*
- ability to carry N dependencies in the command chain
- ability to fetch by multiple columns/key in SQL builders/loaders
- ability to carry complex context via Reference (yay)
- support for DBAL to declare composite FKs (no BC expected, deprecation will be required)
- train schema-builder to automatically define composite inner/outer keys
- scanning logic in ORM and Heap to select by composite key (alternative - optimize on index level)

What needs to be done:
- ability to collect complex reference in Parser/Node (no BC expected, can be done via combined references "key1.key2.key3...")
- ability to define complex reference in relations (no BC expected)
- ability to quickly index entity based on composite PK in ORM and Heap (no BC expected)
- disable 1 PK validation
- ensure that composite PKs always require app specific values (DatabaseMapper level)
- improve relations to support composite inner/outer keys (schema update)
- minor optimizations in context producers and consumers to simplify binding the dependency on multiple values (memory optimization)

**Comment by wolfy-j** [comment]
Heap can use composite keys now.

**Comment by guilhermeaiolfi** [comment]
I am starting a new project now that has composite keys in it, and I am looking for a ORM or data abastraction layer to use. I discovered cycle today and I liked what I've seen. I am testing it right now and I was wondering how far away you are to 1.3.0.  Is there any other place I could ask those questions? I couldn't find any discord, forum, slack channel.

**Comment by wolfy-j** [comment]
Hi,

you can find an active link to our discord channel at the main page: https://github.com/cycle/orm
https://discord.gg/TFeEmCs

We are still in progress on 1.3.0 and currently work on different priority, work on composite PK will be unfrozen somewhere around min Nov once we complete distributed workflow engine integration with Temporal.
