### ISSUE TITLE
Добавить формат сохранения даты и времени в аннотацию Column

### ISSUE THREAD

**Issue by only-viktor** [cycle/orm#232]
Предложение добавить формат сохранения даты и времени для полей типа `timestamp`, `datetime`, `time`, `date` в аннотацию `@Column()`.

Иногда требуется сохранять и микросекунды, к примеру для сортировки по времени создания сущности:
```
/**
 * @Cycle\Column(type="datetime('Y-m-d H:i:s.u')")
 */
private DateTimeImmutable $creationTime;
```
Или к примеру мне нужно сохранять только часы и минуты:
```
/**
 * @Cycle\Column(type="time('H:i:00')")
 */
private DateTimeImmutable $consultationTime;
```

**Comment by roxblnfk** [comment]
В ORM v2 будет возможность индивидуально для каждой сущности подменить имплементацию класса `TypecastInterface`, в которой и [обрабатываются все правила тайпкаста](https://github.com/cycle/orm/blob/c36c7192996869c361a4318e61bbf856b356aef4/src/Parser/Typecast.php#L40-L73).

**Comment by only-viktor** [comment]
По-моему `typecast` тут не поможет. 

Во-первых, `typecast` выполняется после получения данных из базы и конвертирует во внутренний тип в php, а в задаче нужно наоборот, конвертировать дату перед сохранением в базу.

Во-вторых в методе `Spiral\Database\Driver\Driver::bindParameters()` выполняется метод `formatDatetime()`, который  конвертирует дату в строку в формате указанном в константе `protected const DATETIME = 'Y-m-d H:i:s'`, а в задаче требуется сохранять другом формате.

**Comment by only-viktor** [comment]
Да, так работает. Спасибо!

**Comment by roxblnfk** [comment]
Благодарю за фидбек и классный кейс :)
