### ISSUE TITLE
Не работает сортировка при ленивой загрузке

### ISSUE THREAD

**Issue by roquie** [cycle/orm#249]
<img width="679" alt="Screenshot 2021-11-14 at 15 23 18" src="https://user-images.githubusercontent.com/3214290/141681808-b5eceac9-7f95-4eae-91b5-2442b1c540a8.png">
<img width="707" alt="Screenshot 2021-11-14 at 15 22 55" src="https://user-images.githubusercontent.com/3214290/141681811-9efc616a-e8e7-4b1b-b464-c6f8c203ba35.png">
<img width="621" alt="Screenshot 2021-11-14 at 15 22 45" src="https://user-images.githubusercontent.com/3214290/141681819-24d7ba52-fb38-4a43-8f11-23807df49a0b.png">

> На скринах: репозиторий, энтити и контроллер.
При подобной выгрузке сортировка не работает. Причем выгрузка максимально-тривиальная, а не сложная.

> Не работает с ленивой загрузкой. С жадной работает.

**Comment by msmakouz** [comment]
Hello, which version of Cycle ORM are you using?
We've fixed the sorting in this MR:
https://github.com/cycle/orm/pull/221
Is the problem still reproducible?

**Comment by roquie** [comment]
> Hello, which version of Cycle ORM are you using?

v1 :(
