### ISSUE TITLE
Optimistic lock support 

### ISSUE THREAD

**Issue by wolfy-j** [cycle/orm#27]
Simple mapper modification to issue different command set for queue update and queue delete with version check.

**Comment by mishfish** [comment]
Do you mean add something like @Version annotation for schema description?

**Comment by wolfy-j** [comment]
Hi, technically it will require the development of custom Mapper which can be enabled via schema generator and annotation. But yes, it will be version column driven. Architecture is ready for that.

**Comment by fractalzombie** [comment]
What about optimistic lock at this moment?

**Comment by wolfy-j** [comment]
Feature development is currently on hold (till the end of the year). We are working on a new massive component (https://github.com/temporalio/proposals/blob/master/php/php-rr-sdk.md) which consumes all the team attention. You can implement this feature by youself vis custom command in your mapper.

**Comment by rauanmayemir** [comment]
Could this be squeezed in for V2?

**Comment by roxblnfk** [comment]
> Could this be squeezed in for V2?

This is done as entity behavior
https://github.com/cycle/entity-behavior/
