### ISSUE TITLE
[Feature Request] iterator without entity 

### ISSUE THREAD

**Issue by sergey-telpuk** [cycle/orm#296]
Hello! 
I'm trying to fetch a list, and I wouldn't like to make up an entity. Do I have a chance to use `iterator` without making an entity for each item?

**Comment by roxblnfk** [comment]
You can use `Select::fetchData` method to get data without entity making.

**Comment by sergey-telpuk** [comment]
Sorry, I meant `generator`. I dont want to get all data at once

**Comment by roxblnfk** [comment]
OK, i got it.
Right now it is impossible without hacks.

I think we can add new method like `getDataIterator(bool $typecast = true)`.
I'll discuss it with the team.

**Comment by roxblnfk** [comment]
I looked at the selection code and came to the conclusion that this method will be useless.

And here's why:
Right now the Select::getIterator() method calls the [`$node->getResult()`](https://github.com/cycle/orm/blob/1a72ddcce13b4854b8e012751f69781037483ec5/src/Select.php#L414) method that [returns an array](https://github.com/cycle/orm/blob/1a72ddcce13b4854b8e012751f69781037483ec5/src/Parser/OutputNode.php#L31-L34) as result.
It means the data loading isn't lazy.

You can use just `ArrayIterator` to convert an array to an iterable object ¯\\\_(ツ)\_/¯
