### ISSUE TITLE
[Cycle 2.0] Cycle\ORM\Exception\SchemaException : Undefined schema `xxxx`, not found.

### ISSUE THREAD

**Issue by stelpuknewageio** [cycle/orm#302]
Hi, I try to embed Value Object to more two entities. But I have such error Cycle\ORM\Exception\SchemaException : Undefined schema `xxxxx`, not found. in cycle 1.18 it works. I guess after schema normalizer we have a lost role

**Comment by sunxyw** [comment]
I seem to be having the same problem with Many to Many relation, any fixes?

An error says that the schema of the pivot model cannot be found.

**Comment by roxblnfk** [comment]
Hi @sunxyw
Could you share definition of Pivot class and MTM relation?

**Comment by roxblnfk** [comment]
About embeddings to more two entities - it was introduced after 2.0
