### ISSUE TITLE
Support of psr/container:^2.0 for Symfony 6

### ISSUE THREAD

**Issue by rela589n** [cycle/orm#320]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Hello! When using scratch symfony application it is not possible to use cycle orm as `symfony/service-contracts:3.0` requires  `psr/container:^2.0` which is not supported by cycle.

### Version

```shell
ORM 2.0.0
PHP 8.1.1
Symfony 6.0.2
```

**Comment by roxblnfk** [comment]
Should be fixed with Spiral Framework 2.9 release

**Comment by roxblnfk** [comment]
Hello. Issue was fixed in Spiral Framework 2.9.
Can you check it?
