### ISSUE TITLE
Many to Many pivoted table bug🐛 

### ISSUE THREAD

**Issue by BelaRyc** [cycle/orm#322]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

If on pivoted table exists unique index we have error when clear old relation and set same new

Cycle first inserts into the Pivoted table, and only then deletes old records

Repository to reproduce: https://github.com/BelaRyc/cycle-relation-bug

### Version

```shell
ORM 2.0.0
PHP 8.1
```

**Comment by roxblnfk** [comment]
Fix will be released in few days. Thanks a lot.
