### ISSUE TITLE
🐛 ORM hydrator can't fill behavior fields

### ISSUE THREAD

**Issue by roquie** [cycle/orm#323]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

How to reproduce?
1. Install cycle orm with entity-behavior package
```json
"cycle/orm": "^2",
"cycle/entity-behavior": "^1.0",
```
2. Register `CreatedAt` and `UpdatedAt` behaviors via php attributes using any entity your like
```php
# e.g.
#[
    Cycle\Entity(repository: Repository\User::class, scope: Scope\NotDeleted::class),
    Behavior\Uuid\Uuid6(field: 'id'),
    Behavior\CreatedAt(column: 'created_at'),
    Behavior\UpdatedAt(column: 'updated_at'),
    Behavior\SoftDelete(column: 'deleted_at'),
]
class User 
{
   #[Cycle\Column(type: 'datetime')]
    private DateTimeImmutable $createdAt;

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }
}
```
3. Please try to select data from table
```php
$userRepository->all();
```

You're should get an error:
```bash
Typed property App\\Entity\\User::$createdAt must not be accessed before initialization
```

I will expect when `$createdAt` filled from database recordset but isn't happened.

### Version

```shell
ORM 2.0.2
Entity-behavior: 1.1.0
PHP 8.1
```

**Comment by msmakouz** [comment]
@roquie 
Hi, I tried to reproduce this issue and created a simple example:
https://github.com/msmakouz/app/tree/orm-issue-323

created_at field corrects filled by Entity Behaviour and correctly hydrated by Cycle ORM.

Can you create an example with this bug? (or modify my example: https://github.com/msmakouz/app/tree/orm-issue-323)
Thanks!
![test](https://user-images.githubusercontent.com/67324318/154287839-8649b703-f82c-45a1-8bda-df4e6f627036.jpg)

**Comment by msmakouz** [comment]
@roquie Do you have any updates?

**Comment by roquie** [comment]
Oh sorry, I missed notification. Okay, I try again.

**Comment by roquie** [comment]
I tried it twice. It's my mistake, sorry.
