### ISSUE TITLE
ManyToMany error Transaction can't be finished. Some relations can't be resolved🐛 

### ISSUE THREAD

**Issue by only-viktor** [cycle/orm#329]
### What happened?

<details>
У меня есть две сущности `User` и `Tag` со связью `ManyToMany`.

Если в обоих сущностях указать связь `ManyToMany`, то возникает ошибка  `Transaction can't be finished. Some relations can't be resolved`

Для воспроизведения ошибки, я взял ваш тест `Cycle\ORM\Tests\Functional\Driver\Common\Relation\ManyToMany\ManyToManyRelationTest` и добавил в метод `getSchemaArray()` связь `ManyToMany` для `Tag::class`:
</details>

I have two entities `User` and `Tag` related with the `ManyToMany` relation

If the `ManyToMany` relation is specified in both entities, then an error will be thrown with the message `Transaction can't be finished. Some relations can't be resolved`

To reproduce that case you can use the `Cycle\ORM\Tests\Functional\Driver\Common\Relation\ManyToMany\ManyToManyRelationTest` test case and add the `ManyToMany` relation for the `Tag::class` (in the `getSchemaArray()` method) as below:

```
         Tag::class => [
                ...
                Schema::RELATIONS => [
                    'users' => [
                        Relation::TYPE => Relation::MANY_TO_MANY,
                        Relation::TARGET => User::class,
                        Relation::SCHEMA => [
                            Relation::CASCADE => true,
                            Relation::THROUGH_ENTITY => TagContext::class,
                            Relation::INNER_KEY => 'id',
                            Relation::OUTER_KEY => 'id',
                            Relation::THROUGH_INNER_KEY => 'tag_id',
                            Relation::THROUGH_OUTER_KEY => 'user_id',
                        ],
                    ],
                ],
            ],
```

<details>
Результат выполнения теста `testUnlinkManyToManyAndReplaceSome()`:
</details>

After  `testUnlinkManyToManyAndReplaceSome()` calling you will see that error:

```
Cycle\ORM\Exception\TransactionException : Transaction can't be finished. Some relations can't be resolved:
Create new `tag_context`
 - tag.users:tag_context (Cycle\ORM\Relation\ShadowBelongsTo)
 /app/vendor/cycle/orm/src/Exception/TransactionException.php:40
 /app/vendor/cycle/orm/src/Transaction/UnitOfWork.php:104
 /app/vendor/cycle/orm/src/Transaction.php:48
 /app/app/src/Example/Functional/Driver/Common/BaseTest.php:248
 /app/app/src/Example/Functional/Driver/Common/Relation/ManyToMany/ManyToManyRelationTest.php:403
```

### Version

```shell
ORM 2.0.0
PHP 8.0
```

**Comment by albertborsos** [comment]
I have the same issue. It works if I use as in the [documentation](https://cycle-orm.dev/docs/relation-many-to-many), but if I want to get the users from a `Tag`, I have to add the `ManyToMany` relation to `Tag` entity. I can query the relation, but when I want to store a new `User` with `Tag`, then I get the following error:
```
Transaction can't be finished. Some relations can't be resolved:  
  Create new `userTag`                                           
   - tag.users:userTag (Cycle\ORM\Relation\ShadowBelongsTo)
```

**Comment by roxblnfk** [comment]
@albertborsos can you show the ORM Schema (relations `tag.users` and `users.tag`)?

**Comment by albertborsos** [comment]
I just updated my error for this ticket 😊  For real, I have articles and tags. here is my `schema.php`

```php
<?php

declare(strict_types=1);

use Cycle\ORM\Relation;
use Cycle\ORM\SchemaInterface as Schema;

return [
    'article' => [
        Schema::ENTITY => 'App\\Entity\\Article',
        Schema::MAPPER => 'Cycle\\ORM\\Mapper\\Mapper',
        Schema::SOURCE => 'Cycle\\ORM\\Select\\Source',
        Schema::REPOSITORY => 'App\\Repository\\ArticleRepository',
        Schema::DATABASE => 'database',
        Schema::TABLE => 'article',
        Schema::PRIMARY_KEY => ['id'],
        Schema::FIND_BY_KEYS => ['id'],
        Schema::COLUMNS => [
            'id' => 'id',
            'externalId' => 'external_id',
            'source' => 'source',
            'title' => 'title',
            'link' => 'link',
            'imageUrl' => 'image_url',
            'publishedAt' => 'published_at',
            'createdAt' => 'created_at',
        ],
        Schema::RELATIONS => [
            'tags' => [
                Relation::TYPE => Relation::MANY_TO_MANY,
                Relation::TARGET => 'tag',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::WHERE => [],
                    Relation::ORDER_BY => [],
                    Relation::INNER_KEY => ['id'],
                    Relation::OUTER_KEY => ['id'],
                    Relation::THROUGH_ENTITY => 'articleTag',
                    Relation::THROUGH_INNER_KEY => 'article_id',
                    Relation::THROUGH_OUTER_KEY => 'tag_id',
                    Relation::THROUGH_WHERE => [],
                    '4' => null,
                ],
            ],
        ],
        Schema::SCOPE => null,
        Schema::TYPECAST => [
            'id' => 'int',
            'publishedAt' => 'datetime',
            'createdAt' => 'datetime',
        ],
        Schema::SCHEMA => [],
        Schema::LISTENERS => [
            [
                'Cycle\\ORM\\Entity\\Behavior\\Listener\\CreatedAt',
                [
                    'field' => 'createdAt',
                ],
            ],
        ],
        Schema::TYPECAST_HANDLER => null,
    ],
    'articleTag' => [
        Schema::ENTITY => 'App\\Entity\\ArticleTag',
        Schema::MAPPER => 'Cycle\\ORM\\Mapper\\Mapper',
        Schema::SOURCE => 'Cycle\\ORM\\Select\\Source',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::DATABASE => 'database',
        Schema::TABLE => 'article_tag',
        Schema::PRIMARY_KEY => ['id'],
        Schema::FIND_BY_KEYS => ['id'],
        Schema::COLUMNS => [
            'id' => 'id',
            'createdAt' => 'created_at',
            'article_id' => 'article_id',
            'tag_id' => 'tag_id',
        ],
        Schema::RELATIONS => [],
        Schema::SCOPE => null,
        Schema::TYPECAST => [
            'id' => 'int',
            'createdAt' => 'datetime',
            'article_id' => 'int',
            'tag_id' => 'int',
        ],
        Schema::SCHEMA => [],
        Schema::LISTENERS => [
            [
                'Cycle\\ORM\\Entity\\Behavior\\Listener\\CreatedAt',
                [
                    'field' => 'createdAt',
                ],
            ],
        ],
        Schema::TYPECAST_HANDLER => null,
    ],
    'tag' => [
        Schema::ENTITY => 'App\\Entity\\Tag',
        Schema::MAPPER => 'Cycle\\ORM\\Mapper\\Mapper',
        Schema::SOURCE => 'Cycle\\ORM\\Select\\Source',
        Schema::REPOSITORY => 'App\\Repository\\TagRepository',
        Schema::DATABASE => 'database',
        Schema::TABLE => 'tag',
        Schema::PRIMARY_KEY => ['id'],
        Schema::FIND_BY_KEYS => ['id'],
        Schema::COLUMNS => [
            'id' => 'id',
            'name' => 'name',
        ],
        Schema::RELATIONS => [
            'articles' => [
                Relation::TYPE => Relation::MANY_TO_MANY,
                Relation::TARGET => 'article',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::WHERE => [],
                    Relation::ORDER_BY => [],
                    Relation::INNER_KEY => ['id'],
                    Relation::OUTER_KEY => ['id'],
                    Relation::THROUGH_ENTITY => 'articleTag',
                    Relation::THROUGH_INNER_KEY => 'tag_id',
                    Relation::THROUGH_OUTER_KEY => 'article_id',
                    Relation::THROUGH_WHERE => [],
                    '4' => null,
                ],
            ],
        ],
        Schema::SCOPE => null,
        Schema::TYPECAST => [
            'id' => 'int',
        ],
        Schema::SCHEMA => [],
        Schema::TYPECAST_HANDLER => null,
    ],
];

```
And the error what I got:
```
In TransactionException.php line 40:
                                                                    
  Transaction can't be finished. Some relations can't be resolved:  
  Create new `articleTag`                                           
   - tag.articles:articleTag (Cycle\ORM\Relation\ShadowBelongsTo)   
                                                                    

#0 /var/www/app/vendor/cycle/orm/src/Transaction/UnitOfWork.php(104): Cycle\ORM\Exception\TransactionException::unresolvedRelations(Array, Object(Cycle\ORM\Service\Implementation\RelationProvider))
#1 /var/www/app/vendor/cycle/orm/src/Transaction.php(48): Cycle\ORM\Transaction\UnitOfWork->run()
#2 /var/www/app/vendor/yiisoft/yii-cycle/src/Data/Writer/EntityWriter.php(30): Cycle\ORM\Transaction->run()

```

**Comment by roxblnfk** [comment]
@albertborsos can you add this value in the schema?

```
$schema['tag'][Schema::RELATIONS]['articles'][Relation::SCHEMA][Relation::INVERSION] = 'tags';
```


<details>

```php
    'tag' => [
        Schema::ENTITY => 'App\\Entity\\Tag',
        Schema::PRIMARY_KEY => ['id'],
        Schema::COLUMNS => [
            'id' => 'id',
            'name' => 'name',
        ],
        Schema::RELATIONS => [
            'articles' => [
                Relation::TYPE => Relation::MANY_TO_MANY,
                Relation::TARGET => 'article',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::WHERE => [],
                    Relation::ORDER_BY => [],
                    Relation::INNER_KEY => ['id'],
                    Relation::OUTER_KEY => ['id'],
                    Relation::THROUGH_ENTITY => 'articleTag',
                    Relation::THROUGH_INNER_KEY => 'tag_id',
                    Relation::THROUGH_OUTER_KEY => 'article_id',
                    Relation::THROUGH_WHERE => [],
                    Relation::INVERSION => 'tags',           // <====
                    '4' => null,
                ],
            ],
        ],
    ],
```

</details>

**Comment by albertborsos** [comment]
@roxblnfk I get the same error.

**Comment by albertborsos** [comment]
@roxblnfk is there any way I can configure this inversion value via php attributes? I did not find it in the documentations. Thanks

**Comment by roxblnfk** [comment]
> @roxblnfk is there any way I can configure this inversion value via php attributes? I did not find it in the documentations. Thanks

Right now there is no simple way yet

Hard way: you can add custom [SchemaModifier](https://github.com/cycle/schema-builder/blob/2.x/src/SchemaModifierInterface.php) implementation

For example:

<details>

```php
#[Attribute(flags: Attribute::TARGET_CLASS)]
class ModifySchema implements \Cycle\Schema\SchemaModifierInterface
{
    private string $role = '';

    public function __construct(private array $schema) {}


    public function withRole(string $role): static
    {
        $clone = clone $this;
        $clone->role = $role;
        return $clone;
    }

    public function compute(\Cycle\Schema\Registry $registry): void {}

    public function render(\Cycle\Schema\Registry $registry): void {}

    public function modifySchema(array &$schema): void
    {
        $this->merge($this->schema, $schema);
	}

    private function merge(array $from, array &$to): void
    {
        foreach ($from as $key => $value) {
            if (!array_key_exists($key, $to) || !is_array($to[$key])) {
                $to[$key] = $value;
                continue;
            }
            if (!is_array($value)) {
                $to[$key][] = $value;
                continue;
            }
            $this->merge($value, $to[$key]);
		}
    }
}

#[ModifySchema([Schema::RELATIONS => ['articles' => [Relation::SCHEMA =>[Relation::INVERSION => 'tags']]]])]
class Tag {}
```

</details>

**Comment by albertborsos** [comment]
Thanks!

With this modification:
```php
    public function modifySchema(array &$schema): void
    {
        $this->merge($this->schema['value'], $schema);
    }
```
it generates the expected schema, but still not works.

I tried to add the inverted inversion to `Article`, but I still get the same error.

**Comment by albertborsos** [comment]
~~@roxblnfk I found out what was the issue.~~

~~I use yii3 and the `yiisoft/yii-demo` app uses `Yiisoft\Yii\Cycle\Data\Writer\EntityWriter` class from `yiisoft/yii-cycle:2.0.x-dev` and `EntityWriter` uses `Cycle\ORM\Transaction` which is deprecated...~~

~~I have just updated my code to persist with `EntityManager` and it works now.~~

It still occurs... I found out that it fails when I assign an existing Tag to a new Article.

**Comment by albertborsos** [comment]
The real exception occured in `src/Transaction/Pool.php:L261` with `Pool has gone into an infinite loop.` exception message

Can I help to resolve this with some data from xdebug?

I can send more details from these objects.

```
$item = {Cycle\ORM\Transaction\Tuple} [8]
$pool = {SplObjectStorage} [1]
$entity = {App\Entity\ArticleTag Cycle ORM Proxy} [3]
$this = {Cycle\ORM\Transaction\Pool} [9]
$tuple = {Cycle\ORM\Transaction\Tuple} [8]
$stage = {int} 2
$hasUnresolved = true
```

**Comment by roxblnfk** [comment]
> Can I help to resolve this with some data from xdebug?

If you can make a PR with a test that reproduces the problem, that would be a great help

**Comment by TiaNex-Com** [comment]
product has many productSkus
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-kg' for key 'mt_product_sku.mt_product_sku_index_product_id_attribute_name_61a108014425b'
(1-kg ,"1" is product id and "kg" is attribute name)

string(194) "INSERT INTO mt_product_sku (sequence, status, created_at, updated_at, ip_address, product_id, attribute_name, weight, price, quantity) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"

the right action should be delete the same rows or ON DUPLICATE KEY UPDATE

2.Many To Many (product and category)
when add new category to product , error happend but remove
Transaction can't be finished. Some relations can't be resolved: Create new productCategory - category.products:productCategory (Cycle\ORM\Relation\ShadowBelongsTo)

--------------------------------------------------------------
problems 2
public function addCategory(Category $value): void {
        $this->categories?->add($value);
        $this->categories->setPivot($value,new ProductCategory($this->id,$value->getId()));   
    }

$this->categories->setPivot($value,new ProductCategory($this->id,$value->getId()));    //when i add this line

similar to problem 1 error happened

string(77) "INSERT INTO `mt_product_category` (`product_id`, `category_id`) VALUES (?, ?)"
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-37' for key 'mt_product_category.mt_category_product_index_product_id_category_id_60ce685680717'

here is some problems (althoug it's not a right way to compare the different object,but it won't affect the final result,it will delete all the old nodes)

![1](https://user-images.githubusercontent.com/8756686/170655770-d0f441ad-b0ac-4af8-b78c-e47b45642cb8.png)
![2](https://user-images.githubusercontent.com/8756686/170655780-47941bd6-749a-47cd-b434-ff13fac8edd2.png)

i spend 3-4 days on it, i still can't make sure the work flow of orm exactly，
i have a temp  solution,at least my error disapeared now,
1. /src/Transaction/Pool.php
move the delete action from strage 2 to strage 1,,so the transaction will proferm delete prior to instert
 if ($tuple->task === Tuple::TASK_DELETE) {
                        $tuple->task = Tuple::TASK_FORCE_DELETE;
                    }
 if ($tuple->task !== Tuple::TASK_FORCE_DELETE && $tuple->status !== Tuple::STATUS_WAITING ) {
                        continue;
 }
 

2./src/Relation/ManyToMany.php in function
protected function newLink(Pool $pool, Tuple $tuple, PivotedStorage $storage, object $related)

after 

foreach ($this->throughInnerKeys as $i => $pInnerKey) {
            $pTuple->state->register($pInnerKey, $tuple->state->getTransactionData()[$this->innerKeys[$i]] ?? null);

            // $rState->forward($this->outerKeys[$i], $pState, $this->throughOuterKeys[$i]);
        }


add 

 foreach ($this->throughOuterKeys as $i => $pOuterKey) {
            $pTuple->state->register($pOuterKey, $rTuple->state->getTransactionData()[$this->outerKeys[$i]] ?? null);
          
        }


it will add full data values for $pivot table,

i hope it will help,

**Comment by roxblnfk** [comment]
Can you confirm that bug has been fixed?

**Comment by albertborsos** [comment]
@roxblnfk looks good now.
