### ISSUE TITLE
fetchOne() overrides current entity

### ISSUE THREAD

**Issue by albertborsos** [cycle/orm#33]
I do not know this is by design or not, but I think it is a strange behavior.

This is my use case:

I have an entity, and I would like to check this entity exists or not in the database. A simplified example:

```php
class CustomerRepository
{
    public function exists($entity)
    {
        /** @var \Cycle\ORM\Select $select */
        $select = $this->select();
        // .. adding conditions based on primary keys
        return $this->fetchOne() !== null;
    }
}
```

After calling `fetchOne` my `$entity` instance is overridden with the result of `fetchOne`

**Comment by wolfy-j** [comment]
Hi, this is indeed by design and caused by data merge with cyclic relations. Every entity fetch from database will actualize entity state, otherwise the result will be disambiguous. I would recommend use count() for exists check. Let me know if you see any issues with this behavior.

**Comment by wolfy-j** [comment]
However, I think I see what you trying to achieve, let me check how to decouple cyclic loading from already exists entities to avoid custom value overwrite.

**Comment by wolfy-j** [comment]
@albertborsos the fix will be available in 1.1.13, we need about 40 mins to complete all the tests.

**Comment by albertborsos** [comment]
That was fast! Thanks!

**Comment by wolfy-j** [comment]
Releases. Though, I still recommend you to use `count()` to check the existence.

**Comment by albertborsos** [comment]
Now, I have more issues than before.

Here is one of my test:
The first entity is loaded from the ORM, the second `$dbEntity` is loaded via Yii's native db connection.
The entity via cycle ORM has different values than values are exists in the database.
The values are loaded via cycle are the same values as the values are used in the previous test case.
Looks like it is cached.

![Képernyőfotó 2019-09-24 - 13 01 19](https://user-images.githubusercontent.com/7307145/65506493-f3b58e00-decb-11e9-9bb1-17d6ce684a6d.png)

**Comment by wolfy-j** [comment]
Correct, you are using same entity heap between tests. DataMappers track all entity references in memory so this is expected behavior.

Call `$orm->getHeap()->clean();` between tests (tearDown) or clone ORM to isolate each test.

**Comment by wolfy-j** [comment]
Same rules as for daemonized applications: https://github.com/cycle/docs/blob/master/advanced/daemonizing.md

**Comment by albertborsos** [comment]
Thanks, now it is OK!
