### ISSUE TITLE
🐛  Transaction can't be finished. Some relations can't be resolved. Delete `User`.

### ISSUE THREAD

**Issue by roquie** [cycle/orm#346]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Schema generated automatically from attributes.

1. A `User` entity has `HasOne` relation with `UserStatus` where she has multiple deleted items and one not deleted (feature where user has status history). 
2. NotDeleted scope configured.
3. If actor wants to delete a user we got an error above if repository configured to load status using eager loading.

Entity:

```php
class User {
    #[Cycle\Relation\HasOne(
        target: UserStatus::class,
        fkOnDelete: 'CASCADE'
    )]
    private UserStatus $status;
}
```

Repository:

```php
    public function find(
        UuidInterface $id
    ): ?Entity\User {
        return $this->select()
//            ->load('status')  <-- comment is a fix, without comment I got an error with transaction
            ->wherePK($id)
            ->fetchOne();
    }

```

### Version

```shell
ORM 2.1.0
PHP 8.1
```

**Comment by roquie** [comment]
https://github.com/cycle/orm/issues/329

**Comment by roxblnfk** [comment]
Hi.
https://github.com/cycle/orm/issues/329 has been resolved.
Is the issue actual?

**Comment by roquie** [comment]
I think not
