### ISSUE TITLE
add `andFilterWhere` condition

### ISSUE THREAD

**Issue by albertborsos** [cycle/orm#35]
It would be a nice feature to write code like this:
```php
// grid filtering conditions
$select->andFilterWhere('code', 'like', $entity->code);
$select->andFilterWhere('name', 'like', $entity->name);
```
instead of this:
```php
// grid filtering conditions
if ($entity->code !== null) {
    $select->andWhere('code', 'like', $entity->code);
}
if ($entity->name !== null) {
    $select->andWhere('name', 'like', $entity->name);
}
```
I tried to implement it, but I do not really understand yet how it works.

**Comment by genhoi** [comment]
You can do this with custom repositories

```
class UserRepository extends Repository
{

    public function withFilterWhere($column, $operator, $value)
    {
        $r = $this;
        if ($value !== null) {

            $r = clone $this;
            $r->select->where($column, $operator, $value);
        }

        return $r;
    }
}

```
Sample usage
```
        $code = 1;
        $name = 'cat';

        /** @var UserRepository $repo */
        $repo = $this->orm->getRepository(User::class);

        $users = $repo
            ->withFilterWhere('code', 'like', $code)
            ->withFilterWhere('name', 'like', $name)
            ->findAll();
```
https://github.com/cycle/docs/blob/master/basic/repository.md
https://github.com/cycle/docs/blob/master/advanced/chained-repository.md

**Comment by wolfy-j** [comment]
Hi @albertborsos 

I'm against adding this feature for 3 main reasons:
1) The method is confusing, should it skip condition when the value is null/false/empty string?
2) We are saving 2 lines of code but introducing a new concept of optional conditions, this will make code maintenance harder down the road.
3) As @genhoi it's much easier to add custom filter logic to repositories (which they are intended for). 

Thanks for your suggestion, I'm open to change my opinion if more arguments will surface, this ticket will remain open for the discussion for the next few months.

**Comment by albertborsos** [comment]
Thanks! This solution is good enough for me.
