### ISSUE TITLE
Entity subscribers/listeners support?

### ISSUE THREAD

**Issue by rustamwin** [cycle/orm#36]

**Comment by wolfy-j** [comment]
Hi, this can be achieved using custom mapper implementation as it has full control over the entity life-cycle. Custom mappers are very easy to write so events haven't been added to ORM core. 

If this feature is highly demanded we can create an ORM extension with mapper which can be configured using a set of event listenetrs.

**Comment by rustamwin** [comment]
What do you think support for specified entity listeners with annotations
```php
/**
* @BeforeSave()
*/
public function beforeSave()
{
    //..
}
```

**Comment by wolfy-j** [comment]
Sure, something like that can be done using mapper + custom schema generator.

**Comment by wolfy-j** [comment]
Let me know if you want any help creating a package, I think it might work with a fairly small extension. What events do you want to handle?

**Comment by rustamwin** [comment]
> Let me know if you want any help creating a package

I'm busy with other packages right now :) I don't know if I have free time, but I'm trying to help

> What events do you want to handle?

[after]Find
[before/after]Save
[before/after]Delete
[before/after]Create?
[before/after]Update?
and ability add custom events

**Comment by rauanmayemir** [comment]
I wonder if it's not preferable to design a more general use listener/subscriber infra on PSR-14 rather than callback hooks?

Even better if that could be streamlined to work with `spiral/broadcast`.

**Comment by rustamwin** [comment]
> I wonder if it's not preferable to design a more general use listener/subscriber infra on PSR-14 rather than callback hooks?

PSR-14 is a good idea

**Comment by wolfy-j** [comment]
Yeah. I'll check PSR-14. Not sure about broadcast as it has much higher overhead and conceptually should be used for distributed domain-specific events.

**Comment by rauanmayemir** [comment]
@wolfy-j I meant that in a sense that once you have listeners, generating domain-specific events and broadcasting them would be up to the user.

**Comment by wolfy-j** [comment]
Ah, correct.

**Comment by Radiergummi** [comment]
@wolfy-j regarding implementing hooks with a custom mapper - is there any similar example available online? I'm just getting started with Cycle and the mapper paradigm is quite a lot to swallow, so I'm not really sure where to begin. Essentially, I just want to fill my (non-primary key) UUID field before persisting an entity, but the mapper docs don't really cover that...
