### ISSUE TITLE
Migration column with type json is created as text in database (Postgres) 🐛 

### ISSUE THREAD

**Issue by arizanovj** [cycle/orm#393]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Hello. I started working on new project and I am using Cycle. I have a migration created which upon execution is created with wrong column type in the database (Postgres) - instead column of type **json** the column is created with **text** type. This is  part of the code (migration) with the column:

`->addColumn('jsoncolumn', 'json', ['nullable' => false, 'default'  => null])
...
`

### Version

```shell
ORM 2.2.1
PHP 8.2
```

**Comment by msmakouz** [comment]
@arizanovj Hello, should be fixed with a fix in cycle/database: https://github.com/cycle/database/pull/134
