### ISSUE TITLE
[Need Advice] How to create translatable entity field ?

### ISSUE THREAD

**Issue by myavchik** [cycle/orm#40]
How to create translatable entity field ?

**Comment by wolfy-j** [comment]
Can you provide an example? How would you normally do that? 

You can use where condition on related entities to select partial collection.

**Comment by NetLancer** [comment]
I can't understand what database storage has to do with translations (for its table fields), and ORM - to my understanding - is just a more convenient reflection of those table fields and it deals with data that is absolutely necessary to store on the disk (save). And translations probably are not things to persist, but designed for outputting to view dynamically, and basically should be dealt with by some dictionaries which are separate modules crafted within app's architecture..
Though i admit i may misunderstand something :)

**Comment by wolfy-j** [comment]
I assumed the question is about translatable content (like blog posts and etc). But I would agree that this part of domain layer, not the database layer. Though, you can load partial relations to select only specific language:

```php
$posts->load('tranlation', ['load'=>function($q) use ($lang) {
     $q->where('lang', $lang);
}])
```
