### ISSUE TITLE
Primary key

### ISSUE THREAD

**Issue by snezhkoigor** [cycle/orm#42]
```
if ($this->getPrimary($entity) === null) {
```

if in my table primary key === string not uuid?

now I try to do like this

```
/** @Cycle\Column(type = "primary", typecast = "string") */
    public $contract_number;
```

but get error 

```
Cycle\ORM\Exception\ParserException: Unable to parse incoming row: Unable to typecast `contract_number`
```

**Comment by wolfy-j** [comment]
Hi, typecast is a function to call, there is no such function "string". Try:

/** @Cycle\Column(type = "string", primary=true) */

**Comment by wolfy-j** [comment]
Check the column options available: https://cycle-orm.dev/docs/annotated-entity#columns

**Comment by snezhkoigor** [comment]
thanks
