### ISSUE TITLE
Custom type

### ISSUE THREAD

**Issue by snezhkoigor** [cycle/orm#43]
Hi. If I want use some custom types of Postgres? For example "geometry" (postgis).

Try this?

```
class Uuid implements ValueInterface
{
    /** @var UuidBody */
    private $uuid;

    /**
     * @return string
     */
    public function rawValue(): string
    {
        return $this->uuid->getBytes();
    }

    ...
```

**Comment by wolfy-j** [comment]
Yes, but you will have to define the type in the database manually via migration. 

Raw Values are correct approach: https://cycle-orm.dev/docs/advanced-column-wrappers#raw-values

**Comment by snezhkoigor** [comment]
thanks
