### ISSUE TITLE
How to get changed attributes for entity?

### ISSUE THREAD

**Issue by filsh** [cycle/orm#44]
This case need for object activity logging

**Comment by wolfy-j** [comment]
Hi,

you can do it by getting entity properties via `$orm->getMapper($e)->extract($e)` and comparing them to the values from the associated entity node `$orm->getHeap()->get($e)->getData()`. 

More: https://cycle-orm.dev/docs/advanced-entity

**Comment by wolfy-j** [comment]
Inside the mapper you can use State, it will contrain new values.
