### ISSUE TITLE
Filter columns in Select

### ISSUE THREAD

**Issue by mrakolice** [cycle/orm#47]
Is there any opportunities for filtering columns rather than ``select()->buildQuery()->columns()``?

I make some investigation and found that this behaviour can be implemented via implementation of LoaderInterface and so on.

Am I right or in this library exists other way to do what I want?

I want this behaviour:

```
class TestModel
{
    /** @Column(type="string")*/
    public $field1;
    /** @Column(type="string")*/
    public $field2;
    /** @Column(type="string")*/
    public $field3;
    
    public function __construct($field1, $field2, $field3)
    {
        $this->field1 = $field1;
        $this->field2 = $field2;
        $this->field3 = $field3;
    }
}

class TestCase
{
     public function testSelectFields()
     {
        $t = new Transaction($orm)->persist((new TestModel('1', '2', '3')))
        $t->run();
        $result = $orm->getRepository(TestModel::class)->select()->columns(['field1', 'field2'])->fetchOne();

        $this->assertEquals('1', $result->field1);
        $this->assertEquals('2', $result->field2);
        $this->assertNull($result->field3);
     }
}
 ```

**Comment by mrakolice** [comment]
Also, I don't see any opportunities to extend this library on my side, and this makes me very sad. (( Can I refactor it and make customization much easier (I think so, at least =) )?

**Comment by wolfy-j** [comment]
Hi, I will be able to respond in more details after new year eve holidays (our company is off this time). Getting model with partial fields can open a lot of issues in your business logic so we left columns() not reachable intentionally. But, have you checked embedded models? They can be lazy loaded which essentially can be used as safe way to achieve partial loading.

**Comment by wolfy-j** [comment]
https://cycle-orm.dev/docs/relation-embedded#eager-and-lazy-loading

**Comment by mrakolice** [comment]
Unfortunately, embedded entities is not that I want to. ((

In my company we try to build JSON API request parser (like in jsonapi.org) and we need to dynamically choose field getting from database (``fields=field1,field2&fields[related_entity]=field2``) for some issues in our business logic.

**Comment by wolfy-j** [comment]
Hmmm; I don’t think such approach lays down well with ORMs but we can make this https://github.com/cycle/orm/blob/master/src/Select/RootLoader.php#L156 to be customizable.

**Comment by wolfy-j** [comment]
You can also init ORM with custom column schema.

**Comment by mrakolice** [comment]
> Hmmm; I don’t think such approach lays down well with ORMs but we can make this https://github.com/cycle/orm/blob/master/src/Select/RootLoader.php#L156 to be customizable.

This is would be great!

**Comment by mrakolice** [comment]
> You can also init ORM with custom column schema.

So, I just can redefine schema, than do some query stuff and after ``fetchAll()`` can work with whole entity tree?

**Comment by wolfy-j** [comment]
Correct. You can basically create new ORM instance with specific set of columns, that’s what dynamic schema is doing.

**Comment by mrakolice** [comment]
Hmmm... But without some changing in SchemaInterface I'm still not able to do some small manual schema customization. =)

**Comment by mrakolice** [comment]
Schema recreating works at first look, thanks for your response!

**Comment by guilhermeaiolfi** [comment]
I am here after exploring the described solution. It works somehow. But I guess @mrakolice had faced the same problem as I am right now.

Changing the schema may filter the fields for an Entity. But in such queries you may end up needing a set of columns for one Entity and another for a relationship that may be the same Entity. 

For example, imagine that an entity `user` could have many `children` that would reference `user` entity as well. 

Then you can get a query that would like to get all data (all columns) for parents (users) but just the name column for the children (users too).

I know I could filter that after fetching the data from the database, but depending on the column type and its size, that would be unfortunately.

**Comment by roxblnfk** [comment]
> Then you can get a query that would like to get all data (all columns) for parents (users) but just the name column for the children (users too).

Are you sure this case should be covered by the ORM? You're describing a customization at the QueryBuilder level.

By the way, Cycle ORM v2 has new features regarding this issue: you can load data using QueryBuilder and:
- map DB [columns to entity fields and types](https://github.com/cycle/orm/blob/d790848a457d54cce1846ee3d2758fe0ae83537b/src/MapperInterface.php#L32) through a Mapper and continue working with the data in an array without creating incomplete entities.
- use [ORM Iterator](https://github.com/cycle/orm/blob/d790848a457d54cce1846ee3d2758fe0ae83537b/src/Iterator.php#L36) to hydrate entities with values, including relations.
- Create or [get and rehydrate] existing Entity using [ORM::make()](https://github.com/cycle/orm/blob/d790848a457d54cce1846ee3d2758fe0ae83537b/src/ORMInterface.php#L49)

**Comment by guilhermeaiolfi** [comment]
> Are you sure this case should be covered by the ORM? You're describing a customization at the QueryBuilder level.

I know. But that's your fault for creating such a nice project as Cycle. It handles relationships so great that I kind of spoiled and don't want to go back to plain SQL queries.

**Comment by roxblnfk** [comment]
So, I hope the recommendations from the previous message helped you solve the issue.
