### ISSUE TITLE
Configure Constrain on `->load()`

### ISSUE THREAD

**Issue by roxblnfk** [cycle/orm#51]
It would be nice to be able to set a `Constrain` when using the `->load()` method

**Comment by wolfy-j** [comment]
I propose to improve `load` option and support callable instead. This way you can combine both of them. The initial concept was to use Constrains globally rather than custom to the selection.

```php
$select->load('comments', ['load' => new PublicCmments()])
```

What do you think about it?

**Comment by roxblnfk** [comment]
> ```php
> $select->load('comments', ['load' => new PublicCmments()])
> ```
Now it works so that the new Scope (Constraint) is added to the default global Scope.

It would be very cool to be able to replace or disable the default Scope
