### ISSUE TITLE
Why using distinct in limit function?

### ISSUE THREAD

**Issue by mrakolice** [cycle/orm#55]
This behaviour add error on driver level if you are using json fields.
I am using PostgreSQL as RDBMS.

![image](https://user-images.githubusercontent.com/4227668/72778762-922ce280-3c65-11ea-86fe-a35a00a4501c.png)

**Comment by wolfy-j** [comment]
That's a bug, I think we forgot to remove distinct in the last ORM update. Can you create PR with this line removed:

https://github.com/cycle/orm/blob/master/src/Select.php#L181 ?

**Comment by mrakolice** [comment]
Yeah, of course.
