### ISSUE TITLE
Constrain -> Scope

### ISSUE THREAD

**Issue by samdark** [cycle/orm#65]
Constrain is not a good name for a thing since it is a verb. I think it should "constraint".

**Comment by rauanmayemir** [comment]
Also, `scope` would be easier to understand, or `QueryScope`.

**Comment by samdark** [comment]
Yes. Definitely. Scope is even better name.

**Comment by wolfy-j** [comment]
Fun fact, it was called scope during the development.

**Comment by wolfy-j** [comment]
If anyone want to help I’m open to that, but must be no BC.
