### ISSUE TITLE
Move all Cycle ORM repositories to Github Actions

### ISSUE THREAD

**Issue by wolfy-j** [cycle/orm#68]

**Comment by rauanmayemir** [comment]
I'll be happy to help with this.

**Comment by wolfy-j** [comment]
Thank you! I’ve already adapted this repo using your setup for database.

**Comment by rauanmayemir** [comment]
Yes, I saw that. I'll start with `cycle/annotated` and take care of the others.

**Comment by rauanmayemir** [comment]
All repo setups are ready to be merged.
