### ISSUE TITLE
RefersTo innerKey naming error

### ISSUE THREAD

**Issue by vvval** [cycle/orm#78]
Let's say we have 2 entities, which will look like the next ones:
- Entity A:
```php
<?php

declare(strict_types=1);

namespace App;

use Cycle\Annotated\Annotation as Cycle;

/** @Cycle\Entity() */
class A
{
    /** @Cycle\Column(type="int", name="a_key") */
    public $aKey;
}
```
- and entity B:
```php
<?php

declare(strict_types=1);

namespace App;

use Cycle\Annotated\Annotation as Cycle;

/** @Cycle\Entity() */
class B
{
    /** @Cycle\Column(type="int", name="b_key") */
    public $bKey;
}
```

Entity A refers to entity B using `$aKey` and `$bKey` inner/outer keys. Let's add this relation to entity A using property names:
```php
// somewhere inside of entity A
/**
 * @Cycle\Relation\RefersTo(target="B", innerKey="aKey", outerKey="bKey")
 * @var B
 */
public $b;
```

This code will fail on insert because (at least in PostgreSQL) the generated SQL is trying to add both `a_key` and `aKey` columns:
```sql
INSERT INTO "a" (..., "a_key", ..., "aKey") VALUES (..., NULL, ..., <aKey value>)
```
> `a_key` appears to be null, and the `aKey`, which is unknown to the db scheme contains the required value.

As a fix right now, the `referTo` relation should be declared as below:
```php
// somewhere inside of entity A
/**
 * @Cycle\Relation\RefersTo(target="B", innerKey="a_key", outerKey="bKey")
 * @var B
 */
public $b;
```
The SQL will be correct now:
```sql
INSERT INTO "a_named_b_props" (..., "a_key", ...) VALUES (..., <aKey value>, ...)
```

Meanwhile, using `a_key` and `b_key` as inner/outer keys:
```php
// somewhere inside of entity A
/**
 * @Cycle\Relation\RefersTo(target="B", innerKey="a_key", outerKey="b_key")
 * @var B
 */
public $b;
```
leads to a `Cycle\Schema\Exception\SchemaException`
```
Unable to compute relation `a`.'b'
````

**Comment by NiavlysB** [comment]
I had a similar issue with `BelongsTo` with an explicit `outerKey`, where I had to specify the property name instead of the database field.

I’m not 100% sure if it is actually related, but the fix did it for me.
