### ISSUE TITLE
PSR-12 compatibility

### ISSUE THREAD

**Issue by SerafimArts** [cycle/orm#8]
I think that you can follow the PSR-12, which should soon become stable: https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#3-declare-statements-namespace-and-import-statements

## Actual

```php
<?php declare(strict_types=1);
/**
 * Spiral Framework.
 *
 * @license   MIT
 * @author    Anton Titov (Wolfy-J)
 */

namespace Cycle\ORM;
```

## Expected

```php
<?php
/**
 * Spiral Framework.
 *
 * @license   MIT
 * @author    Anton Titov (Wolfy-J)
 */
declare(strict_types=1);

namespace Cycle\ORM;
```

**Comment by SerafimArts** [comment]
P.S. for a quick and automatic fixes the codestyle you can use https://styleci.io/ CI

**Comment by wolfy-j** [comment]
Ugh, I have missed this proposal. That's easy to fix, but since it will affect almost every repository in this and spiral organization proper CS tool is required. Thank you for the suggestion

**Comment by SerafimArts** [comment]
I understood this after I started reading the source code =)

Therefore, instead of closing the issue, I was just corrected it.
