### ISSUE TITLE
Add support for custom persist commands

### ISSUE THREAD

**Issue by wolfy-j** [cycle/orm#9]
Need addCommand method in transaction. Possibly add ability to automatically link to parent context (some user friendly simplification?). Need ability to expose column name resolution for update/delete queries (see resolveAlias of QueryBuilder, split query builder?).

**Comment by SerafimArts** [comment]
I think that the examples with the code will help who did not dig deep into the source code to better understand the problem

**Comment by wolfy-j** [comment]
That’s more a reminder for myself. :) but I will add the example once docs are complete.
