### ISSUE TITLE
How to trace the SQL ?

### ISSUE THREAD

**Issue by dvaknheo** [cycle/orm#90]
I maintained a project used by Cycle ORM , and I want to trace the sql ,log the sql , to debug  the project.
its any config ?

**Comment by wolfy-j** [comment]
You can add any PSR-3 logger to the driver, including monolog or echo to STDERR.

https://github.com/cycle/orm/blob/master/tests/ORM/BaseTest.php#L91

You can get an instance of the driver from DatabaseManager or via `database->getDriver()`
