### ISSUE TITLE
What is the best way to add multiple mappers for entity?

### ISSUE THREAD

**Issue by filsh** [cycle/orm#95]

**Comment by wolfy-j** [comment]
Cycle ORM does not support multiple mappers out of the box for the reason of simplicity. But:

1) You can extend your own mapper from DatabaseMapper.
2) You can request PSR-11 Container in your mapper to load additional functionality.
3) You can create composite mapper and relay on values stored in the SCHEMA segment of Entity schema.

Please let us know the use-case so we can point you to the right direction.

**Comment by filsh** [comment]
I think will make a composite mapper, I thought there is a ready-made solution.
Thanks
